### ISSUE TITLE
express release cadence: feedback request

### ISSUE THREAD

**Issue by gireeshpunathil** [expressjs/discussions#101]
would like to solicit feedback on express release cadence on majors from community members, end users, customers and supporting entities.
 - Verbal as well as graphical feedback welcome!
 - general hint on parameters to consider: easy to migrate, availability of new features, bug fixes, backward compatibility, ...
 - One year or less: please use 👍 
 - Between 1 and 2 years: please use :rocket:
 - Between 2 and 5 years: please use ❤️ 
 - More than 5 years: please use 🎉 

thanks!

**Comment by gireeshpunathil** [comment]
@dougwilson - #67 is talking about faster releases, while this is to solicit feedback from the ecosystem. They are discretely different. Request to re-open this. I am also driving opinions through twitter: https://twitter.com/gireeshpunam/status/1231853658498727936

**Comment by dougwilson** [comment]
So I think the poll options are not well formed. I request we wait until we can discus in the TC meeting so we can make an actual plan for what we want to poll the community on.

**Comment by gireeshpunathil** [comment]
I am covering the most reasonable spectrum of release cadence as possible. Which one do you think is ill-formed? the ranges, or number of ranges?

I am sure no feedback can bring accurate results; but this can be used to collect a pattern or general sentiment.

Sure, let us also discuss in TC to see any / more specific data we could collect from the community!

**Comment by dougwilson** [comment]
Sounds good. I'll close this for discussion in the TC meeting :)

**Comment by dougwilson** [comment]
I haven't forgotten about your two question, either. It is just 3:30am where I am and I need to work tomorrow. I'm sure you can appreciate time zone differences :) I will follow up tomorrow my time.

**Comment by gireeshpunathil** [comment]
@dougwilson - still request you to re-open this issue. Despite what we are going to discuss in the meeting, this issue being open in public for collection of general opinions will help decision making process faster.
