### ISSUE TITLE
Express TC Meeting 02-26-2020 (ad hoc last minute)

### ISSUE THREAD

**Issue by jonchurch** [expressjs/discussions#103]
## Attendance

The entire community is welcome to tune in and observe the meeting live at the time below. The following people are listed here as explicit invitees to get an email notification about the upcoming meeting:

Invited:

@expressjs/express-tc
@expressjs/triagers

## When
Feb 26, 2020 - 23:30 UTC

## Where
**Watch the recording:** https://www.youtube.com/watch?v=_GRZKdu3bKY
Zoom https://zoom.us/j/884354313

* Viewers: https://www.youtube.com/watch?v=_GRZKdu3bKY
* Participants: @dougwilson @wesleytodd @gireeshpunathil @LinusU @HarshithaKP @jonchurch @bethgriggs @mlrawlings 

## Agenda

Request for TC Meeting to talk about 5.0 #99
Express 5.0.0 #100 
Release 5.0 https://github.com/expressjs/express/pull/2237 (Specifically https://github.com/expressjs/express/pull/2237#issuecomment-570058548)
Faster Major Release Schedule https://github.com/expressjs/discussions/issues/67
Document and make official repo captains #98
Express YouTube Channel #94
Express triage #92

**Comment by wesleytodd** [comment]
Notes:

- We decided on 4:00 pm GMT on Thursday March 5th for the next meeting
  - @wesleytodd to get it on the calendar
  - @dougwilson and @wesleytodd  to figure out a better streaming situation before then
- The [list of todo items](https://github.com/expressjs/express/pull/2237#issuecomment-570058548) looks good in general
- Everyone should review the repo capitans proposal as it will be our first topic next week
  - https://github.com/expressjs/discussions/issues/98
- Second agenda item for next week is to follow up on the plan based and divide the work

**Comment by jonchurch** [comment]
@dougwilson ping, can you please update the issue with a link to the recording on youtube once it's available?

**Comment by dougwilson** [comment]
@jonchurch apologies, I left it while it was processing. Linked added above 👍

**Comment by gireeshpunathil** [comment]
resolved, closing
