### ISSUE TITLE
Will v5 Change Node.js Version Support?

### ISSUE THREAD

**Issue by jonchurch** [expressjs/discussions#104]
Will v5 drop support for some Node.js versions? Didn't have time to ask this in the last TC Meeting.

I'm just curious if there are plans for this in v5.

**Note:** I'm not trying to start a discussion about what the plan is or could be, more specifically looking for context about if a decision has been made around this.

**Comment by dougwilson** [comment]
I do have thoughts around this. The short answer is yes, as it is what we already agreed upon. I think the question is ultimately which versions?

Some background: When Express 4 came out, it declared it required Node.js 0.10 or higher. We did not realize this at the time that it would become an issue: Express 4 ran on 0.8. Of course once we later tried to use a 0.10 feature some time later it because a whole thing, as since npm does not actually enforce the constraint, it seems people will not strictly follow it and it became a really hot debate between us at the time and the community as we were "breaking apps".

The gist of the above is that whatever we choose, we should out of the gate make sure it actually doesn't work on versions below that to save everyone grief (both us from issue onslaught and the community from experiencing brokenness).

Originally I was thinking Node.js >= 4 as the requirement, and that is still possible, though I am not sure how many 4 deployments still exist out there. Just between me and myself, I have recently been thinking Node.js >= 6 as that becomes a real cut off we can actually make not work and drop a dependency for: the new Buffer API.

**Comment by jonchurch** [comment]
I know you @dougwilson often use email for updates so you might not have seen my edit that I don't intend to turn this issue into hashing out the policy specifically. 

To address your comment and give context for anyone else, the [`engines`](https://docs.npmjs.com/files/package.json#engines) filed in package.json is only advisory, it'll throw a warning but won't prevent an install.

There's [`process.version`](https://nodejs.org/api/process.html#process_process_version) that can be used to check Node.js versions from the code itself, thus ensuring folks cannot run on unsupported versions by throwing.

I ask this question mostly because I assume that moving the minimum supported version up could allow semver majors of the upstream packages to drop support as well. I'm assuming that also is a whole can of worms as well, which is why I wanted to ask. If we're cutting semver majors of some of the upstream deps for inclusion in v5, then thinking about dropping support in those deps is an important topic.

Like we said in the last TC meeting, there's lots of things that can delay getting v5 out, and I do not want to see this be one.

I assume dropping support in Express would signal that upstreams could consider dropping support too, but with the reliance of other projects on those upstreams, I know that might be a case by case basis.

**Comment by dougwilson** [comment]
> I ask this question mostly because I assume that moving the minimum supported version up could allow semver majors of the upstream packages to drop support as well.

Correct.

> I'm assuming that also is a whole can of worms as well, which is why I wanted to ask. If we're cutting semver majors of some of the upstream deps for inclusion in v5, then thinking about dropping support in those deps is an important topic.
> 
> Like we said in the last TC meeting, there's lots of things that can delay getting v5 out, and I do not want to see this be one.

I agree. I would say that we're not going to through and make a ton of majors of all our internal deps dropping support as part of Express 5. It's more that those deps can drop the major without causing us maintaining headaches of the master line if express not being compatible with the master line of one of our own deps. Many deps do not expose their API directly and we of course can bump an Express dep over a major version as long as it doesn't mean a major in the actual Express API itself. This has been done a few times before.

I think the biggest thing (which is not part of Express 5 work, to be clear) is that it helps drive alignment with the middlewares in expressjs org. To me, the ideal world is that the middlewares should (but not required, especially if they need some particular API or feature) at least support all the same majors as the master version of Express. Sorry about including this here; if you want to hurl rocks at this particular statement, we can move this into a new issue, my bad.

**Comment by jonchurch** [comment]
This was a great clarification thank you @dougwilson.

What I'm taking away as the answer to _"Will v5 drop support for older Node.js version?"_:

> **The short answer is yes, as it is what we already agreed upon.** I think the question is ultimately which versions?

So it has been decided that, yes, there will be changes in supported versions. But what the exact cut off will be has not been decided on yet.

The only reason I stated I don't want to turn this into debate about the specifics of the policy is that I know that's a hot topic and one that might attract drive-by comments and flaming from the world at large, which I don't think helps the v5 effort atm.

**Comment by LinusU** [comment]
Where would be a good place to have the discussion on _which_ version to have as the new minimum? I think it would be good to have a discussion about that and maybe dig up some usage statistics and arguments ☺️

**Comment by wesleytodd** [comment]
I feel like we did have that conversation @LinusU.  IIRC the result was to support the lowest currently maintained versions of node at the time of publish and up.  For example, if we were to publish in March, it would be 10 and up.  Do you see a reason to do otherwise?

**Comment by wesleytodd** [comment]
I see this contradicts what @dougwilson said above, but I think the last time we had this conversation Node 4 was still in this category.  I strongly thing we should force cut official support and required test passing at the current minimum.  But that does not mean purposely break previous versions.  We can even continue to test in them, just make it optional and then have a discussion when we introduce the first real breaking change.

**Comment by dougwilson** [comment]
> IIRC the result was to support the lowest currently maintained versions of node at the time of publish and up. For example, if we were to publish in March, it would be 10 and up. Do you see a reason to do otherwise?

Yes, it was, but since then Node.js has been releasing a major every year since and I think their schedule is quite aggressive, so I think it is fair to question it again now that we are truly on the verge of releasing it.

Do you see anything particularly egregious with my thoughts on it in https://github.com/expressjs/discussions/issues/104#issuecomment-592153592 ?

**Comment by dougwilson** [comment]
Sorry @wesleytodd we cross posted there :joy: . Read my comment above as if it was between your two comments

**Comment by wesleytodd** [comment]
> Do you see anything particularly egregious with my thoughts on it in #104 (comment) ?

Only that we should never suggest to anyone we support Node 6.  It has known performance and security issues.  But I want to be clear, official support and dropping tests are different things 😀

**Comment by dougwilson** [comment]
> Only that we should never suggest to anyone we support Node 6. It has known performance and security issues. But I want to be clear, official support and dropping tests are different things grinning

I definitely agree there. I would see it the same way that we "support" those versions in Express 4 today... my main line of thinking is if we can help folks "stair step" updates, like if they are on Node.js 8, they _could_ go express 5 then Node.js 10. I tend to find internal esoteric code weird mingled with Node.js versions, so almost in a selfish way see this as a way to get them at least off an Express version we don't want to support if they don't want to get off some Node.js versions, but there is a practical line a "pre-modern Node.js" (<4) is definitely under that line to me.

**Comment by wesleytodd** [comment]
This is a great point, and I wonder if we should promoste two separate facts:

1. We officially support and reccomend a minimum of Node 10.x
2. Our tests pass in Node 6.x and up (but this may change at any time)

Then we can change number 2 as we move, but that still gives folks a clear indicator that we do not recommend anything less than node 10.x.  Thoughts on this approach?

**Comment by LinusU** [comment]
> Our tests pass in Node 6.x and up (but this may change at any time)

Personally I'm a bit afraid of doing it this way. I feel that we will get a lot of issues opened if a minor release breaks compatibility for someone.

If we officially support Node.js 10.x and up (which I think that we should ☺️) I think that we should use some language feature present there (e.g. optional catch binding, `trimStart`, etc), or simply have a test that runs when the module is required.

In Multer 2.0, which I released the release candidate the other day for, I set the minimum supported version to Node.js 10.13.0, which was the first 10 version considered LTS. The test matrix is also set up to test `10.13.0`, latest `10`, latest `12` and latest version (right now 13).

**Comment by wesleytodd** [comment]
Totally a valid concern.  I was trying to find a balance between what you describe with Multer and the "well it runs in node 0.10, so I guess it supports 0.10".  I am not a fan of purposely breaking, but I would be fine logging a big deprecation warning if run in less than our supported versions.  Would that maybe suffice?

**Comment by LinusU** [comment]
> I am not a fan of purposely breaking, but I would be fine logging a big deprecation warning if run in less than our supported versions. Would that maybe suffice?

Sounds good to me 👍 

Maybe we also should also commit to not breaking Node.js compatibility in a patch release, so that people still on e.g. Node.js 4 can stick to `~5.0.0`, and then 5.0.x will always be compatible with Node 4, but 5.1.x might not be

**Comment by wesleytodd** [comment]
>  commit to not breaking Node.js compatibility in a patch release

👍
