### ISSUE TITLE
Meeting Today?

### ISSUE THREAD

**Issue by jonchurch** [expressjs/discussions#107]
A tracking issue for a meeting was never created. Are we meeting today?

**Comment by gireeshpunathil** [comment]
I asked it here: https://github.com/expressjs/discussions/issues/100#issuecomment-598000370 I was under the impression that you create those manually.

Either way, @expressjs/express-tc @expressjs/triagers - can we make it in the next 30 minutes? I am ! 

Please indicate here through thumbs up!

**Comment by jonchurch** [comment]
I created the last two because no one else did but didnt get to it this time.

**Comment by gireeshpunathil** [comment]
haven't heard from @dougwilson or @wesleytodd who have the handles to run the TC, so let us deem it cancelled for today!

@expressjs/express-tc - please post your next availability!

**Comment by ryhinchey** [comment]
I’m generally available just need to know ahead of time!

**Comment by wesleytodd** [comment]
Was dealing with changing travel plans so wouldn’t have been able to make it anyway. I think our plan is in action, was there anything specific we needed to talk about anyway?

**Comment by gireeshpunathil** [comment]
> I think our plan is in action, was there anything specific we needed to talk about anyway?

@wesleytodd - If it makes sense to others, I would love to have a working session in the next TC, basically targetting PRs that are low hanging, or having minor differences to ratify. I guess it makes a lot easier if people do it together and land those, especially the ones that are easy ones, ready to land and are ear-marked for 5.

what do you think? If people like it, I could identify a few that we can work it out in the TC. Let me know!

**Comment by jonchurch** [comment]
I do think we are in a good place w/ v5, so meeting today wasn't necessary anyways.

Leaving some notes based on reducing confusion in the future. I've experienced these things in other open source projects as well, and think it's a good idea for project health to address them eventually.

**Takeaways:**

* A meeting was assumed to happen today because we said two meetings ago that we were going to do weekly meetings to check in on v5
* I don't believe we officially documented that decision, or the schedule, outside of issue comments or a recording
* There wasn't a pending issue to track the next meeting, so folks (like myself) weren't sure if it was official. 
* Without key stakeholders (permissions for zoom, streaming), it's unclear how to proceed with an ad hoc meeting if some folks want to hold one

**Remedies:**

* Make sure meeting cadence is committed to the readme, update it when cadence changes (e.g. when we put forward doing weekly)
* Make sure issues are generated to track a meeting. I'm in favor of anyone being able to create them (since they are easily editable/close-able), and suggest it is part of the wrap up of any given meeting. Issues are generated automatically w/ the Node.js projects based on a calendar and [some templates](https://github.com/nodejs/create-node-meeting-artifacts), which we could set up eventually, but let's not overengineer things too early.
* Document procedure for holding ad hoc meetings, or in the case that the main stakeholders aren't available. Can just be `If stakeholders aren't available, start a google hangout, post the link, and have someone record it`

**Comment by jonchurch** [comment]
Should we say next thursday for the next meeting? March 19th, same time as before?

**Comment by dougwilson** [comment]
I would say that if the desire to commit to the given day/time is in order, we need someone who has credentials to hold the meeting to commit to it as well. I have credentials, but it is unfortunate that the meeting is during my working hours and as such, I cannot actually commit to running it or being there every time. I'm not sure what a solution is for who should open the place holder issue while it is manual; maybe a suggestion is the person who will commit to being there as the host (has creds/whatever) should open the issue so it also instills confidence that the meeting will happen at the given date/time with a host there.

I am totally on board with having ad-hoc meetings too; I haven't put any thought beyond liking the idea as for how to accomplish it, so whatever the suggestions are :)

**Comment by dougwilson** [comment]
> Should we say next thursday for the next meeting? March 19th, same time as before?

Just to put this out there (again): I cannot reliably attend the day/time of this meeting. Ideally if this is the TC Meeting, I would really like it to be at a time where the TC members (like myself) can reliably attend it (i.e. the ability to attend is likely vs unlikely). But at the least, someone who can actually host the meeting would probably need to confirm if that can happen or not.

**Comment by Sushmeet** [comment]
For me personally I am willing to try to accommodate a time where the TC members are comfortably available. I say this because as a trigger, if I am unavailable, I am able to catch up on the you tube recording and then chime in after. But the TC members can really help guide the meeting and keeping us honest so it does make a lot of sense to me for being sensitive to their availability. Thanks

**Comment by dougwilson** [comment]
I created the placeholder for the next meeting https://github.com/expressjs/discussions/issues/109 so this does not happen for next week, as I am committed to hosting the meeting for us to know it will happen 👍

**Comment by jonchurch** [comment]
Closing as I think this issue has served it's purpose.
