### ISSUE TITLE
Proposing Triage Team Meetings ( additional, supplementary to TC )

### ISSUE THREAD

**Issue by ghinks** [expressjs/discussions#118]
Originally when I sat opposite of @wesleytodd at the collaborators summit and asked him what success was going to look like as we tried to recruit triage members he replied **"If I could find one".**

We now have a good team of triage members and the outreach that started at that conference is paying dividends. We must not get casual and will still need to keep recruiting as  @gireeshpunathil mentions [here](https://github.com/expressjs/discussions/issues/117).

We are now a large enough group that **triage discussions may need a space**. Every TC meeting runs over by on average 30 minutes.

It has been proposed that we set another meeting space up ( an additional space ) for those triage discussions. 

I would like to solicit opinions on 
- whether we think this is a good idea
- the frequency & time of the proposed meetings
- the length of the proposed meetings

I would also like to suggest that we have a rigid structure insomuch as we stick to the duration allocated in those meetings.

We are an international triage team and there is no **good** time for everyone. Just reasonable times. 

Given the current situations that most of find ourselves in ( all working from home ) we may have more flexibility at the moment than in the future. So If we start on a certain cadence we will accept future changes to any date and frequency these proposed meetings have.

**Comment by wesleytodd** [comment]
>  "If I could find one"

You all have no idea how happy this last meeting made me about our progress! Thanks everyone for stepping up!

**Comment by jonchurch** [comment]
I think the fewer meetings on folks' calendars the better overall. I'm partial to meeting formats for hashing things out, though. 

If we can communicate and coordinate well without needing meetings, awesome. I don't think we are there yet however. I'm in favor of meeting sporadically until we either have a good idea of the necessary role meetings fill, or are communicating well enough asynchronously that we won't need regular meetings.

My opinions for @ghinks questions:

> * whether we think this is a good idea
> * the frequency & time of the proposed meetings
> * the length of the proposed meetings

* I think planning a single meeting is a great idea
* Let's plan this first one as one off and see if we feel the need for another afterwards. The time depends on who plans to attend, but either of the times we've met already work for me in EST
* I think the length should depend on the agenda items, but should have a hard cut off at 1 hour.

**Before we actually plan a meeting, I'd like to see us come up with agenda items for the meeting. To both help us stay organized, but also to figure out what we can answer online vs what is best discussed in a meeting.**

**Comment by ryhinchey** [comment]
I agree with Jon about putting repeating meetings on the books right now.  We probably need a few initial ones to hash out a plan but I think the best long term plan is to find a way to effectively communicate asynchronously (github discussions, slack channel, the express Gitter) in public.

**Comment by ghinks** [comment]
So it sounds like we should have some initial adhoc meetings and proceed from there

**Comment by dougwilson** [comment]
Let me know if you need anything, including if you think i should try to attend one. Zoom accounts are free, though they have a one hour meeting limit (maybe that is lifted right now).

**Comment by ghinks** [comment]
After some thought and taking into account @gireeshpunathil [issue about company help](https://github.com/expressjs/discussions/issues/117) we will need a few separate triage meetings simple to get people **onboarded**. 
I am pretty sure that the talent and willingness exists out there to do basic triage work ( and most of our work is the basic stuff ) then the triage member can graduate to more  responsibilities to support the core.
@jonchurch I am going to do some more promotion within my circles but we will need to setup a triage meet to onboard them. I'll keep you posted I have some meetings today on this subject.

**Comment by ghinks** [comment]
I may have 4 more volunteers for the triage group. I think that we will need some help @jonchurch and have to come up with an onboarding process. I'm still constantly humbled by what I discover each day about the express eco system and starting of humbly is the best approach.

**Comment by ghinks** [comment]
@jonchurch @dougwilson I have some new prospective members for the triage team would like to have **triage** team meeting where we could talk to them and get them "on-boarded". I am not sure of the logistics for doing so. Could we just use a zoom meeting and post the meeting to youtube later, or can we stream directly too. Do we need to contact the openJS foundation in order to get the permissions to do so?

**Comment by jonchurch** [comment]
@ghinks I've been a bit absent this past week, but figuring this out is a priority for me. Would you want to do a brief call 1:1 with me to discuss onboarding and the folks you're hoping to bring in? If a call isn't convenient, we can chat via email.

I suggest a private channel instead of issues bc I expect this to be a casual brainstorming type of thing we can hash out a plan on together.

**Comment by ghinks** [comment]
Excellent idea

**Comment by ghinks** [comment]
Send me a link at glenn@glennhinks.com

**Comment by jonchurch** [comment]
@ghinks Sent

**Comment by ghinks** [comment]
Getting on link

**Comment by gireeshpunathil** [comment]
anything pending on this issue?

**Comment by UlisesGascon** [comment]
This is now revamped in https://github.com/expressjs/discussions/issues/276
