### ISSUE TITLE
Express logo and favicon

### ISSUE THREAD

**Issue by hacksparrow** [expressjs/discussions#12]
As per the last TC meeting (https://github.com/expressjs/discussions/issues/6) and the issue reported at https://github.com/strongloop/expressjs.com/issues/607, we want a logo and a favicon for Express.

Here are the initial two proposals. The font used in the logo is "Helvetica Bold".

1. **"Ex" on a white background**
![512-white](https://cloud.githubusercontent.com/assets/950112/14019794/71e3252a-f1fa-11e5-91f9-b7e77a1c8be8.png)
![256-white](https://cloud.githubusercontent.com/assets/950112/14019711/28c2b6b2-f1fa-11e5-8770-6e16e300b028.png)
![128-white](https://cloud.githubusercontent.com/assets/950112/14019720/2c38fc48-f1fa-11e5-8785-6e4842607aba.png)

2. **"Ex" on a yellow background (themed after the popular "yellow JS logo")**

![512-yellow](https://cloud.githubusercontent.com/assets/950112/14019734/3cf13fd2-f1fa-11e5-8c84-1865c4d505a8.png)
![256-yellow](https://cloud.githubusercontent.com/assets/950112/14019750/40bf6404-f1fa-11e5-89bd-4fd1852ac821.png)
![128-yellow](https://cloud.githubusercontent.com/assets/950112/14019753/42d42554-f1fa-11e5-86e9-9cf07c6bd55e.png)

The favicon will be derived from the logo.

Feedback welcome 😀

**Comment by sjanuary** [comment]
I don't think Helvetica is an open licensed font is it?  [Roboto](https://www.google.com/fonts/specimen/Roboto) might be a good substitute.

**Comment by hacksparrow** [comment]
The font comes on my machine by default, and I am using a licensed copy of Photoshop. Shouldn't that be ok?

Will put up a Roboto version in a short while.

**Comment by hacksparrow** [comment]
Roboto's **X** is kind a ugly 😁

1. **"Ex" on a white background**

![512-roboto-white](https://cloud.githubusercontent.com/assets/950112/14020908/354515b0-f1ff-11e5-821d-8508057003c2.png)
![256-roboto-white](https://cloud.githubusercontent.com/assets/950112/14020910/35e41660-f1ff-11e5-8958-d62fce1c5557.png)
![128-roboto-white](https://cloud.githubusercontent.com/assets/950112/14020912/36a80d7c-f1ff-11e5-8c40-ae7f0517fcf9.png)

2. **"Ex" on a yellow background (themed after the popular "yellow JS logo")**

![512-roboto-yellow](https://cloud.githubusercontent.com/assets/950112/14020914/37874370-f1ff-11e5-98bf-7c498d55a39f.png)
![256-roboto-yellow](https://cloud.githubusercontent.com/assets/950112/14020917/3b298d80-f1ff-11e5-9344-bd30864ced7d.png)
![128-roboto-yellow](https://cloud.githubusercontent.com/assets/950112/14020922/3d67aeba-f1ff-11e5-9e66-5e00d6aed0d6.png)

**Comment by sjanuary** [comment]
I'm not sure, have you checked the license terms for Helvetica?  I think for some fonts you have to purchase an additional license to embed them in a logo.

**Comment by tunniclm** [comment]
![expressjs](https://cloud.githubusercontent.com/assets/5011883/14021158/3ad1ba60-f1d2-11e5-8bd7-ed6e4171b70b.png) ![expressjs32x32](https://cloud.githubusercontent.com/assets/5011883/14021467/7f7f95b4-f1d3-11e5-81cf-dba5f5c000d3.png)

![expressjs3](https://cloud.githubusercontent.com/assets/5011883/14021159/3ed36640-f1d2-11e5-911e-04d85eee559b.png) ![expressjs3_32](https://cloud.githubusercontent.com/assets/5011883/14021221/81586f9c-f1d2-11e5-92e5-848be89e5ca5.png) ![expressjs3_16](https://cloud.githubusercontent.com/assets/5011883/14021229/91337f60-f1d2-11e5-8174-5c3555d475eb.png)

![expressjs4](https://cloud.githubusercontent.com/assets/5011883/14021168/4a8d8114-f1d2-11e5-9b42-e3cf7c9f4a0d.png) ![expressjs4_32](https://cloud.githubusercontent.com/assets/5011883/14021318/e60245da-f1d2-11e5-82f9-1338a801ddc2.png) ![expressjs4_16](https://cloud.githubusercontent.com/assets/5011883/14021319/e602ea76-f1d2-11e5-89b9-2b59110b1d64.png)

![expressjs2](https://cloud.githubusercontent.com/assets/5011883/14021151/31c921c4-f1d2-11e5-8848-c1b34f7a93ac.png) ![expressjs2_32](https://cloud.githubusercontent.com/assets/5011883/14021378/2830637e-f1d3-11e5-9d41-54a6ac83f325.png) ![expressjs2_16](https://cloud.githubusercontent.com/assets/5011883/14021370/22087d06-f1d3-11e5-8f3d-52093c86f84d.png)

**Comment by hacksparrow** [comment]
Looks like we will need to license the use of Helvetica. Fortunately, "E" and "x" are simple shapes, I can create them myself. Will share an update tomorrow.

Mike, 8 instances of Helvetica have been spotted in your submission 😃

**Comment by tunniclm** [comment]
The first 8 are just variations of the logo that is present on github.com/expressjs

**Comment by gabeio** [comment]
if it's all the same I like the small `e` over the big `E`...

**Comment by crandmck** [comment]
I think the lowercase "e" looks better than the capital as well, even though the actual spelling of the framework name is "Express" (capitalized--it's a proper noun).  Of course, in code it's `var express = require('express'); ` so that justifies using lowercase, in my mind at least.  Just my $0.02 as the resident word-obsessive.

**Comment by blakeembrey** [comment]
All lower looks more consistent, and to be fair the logo on https://github.com/expressjs/express has always been lowercase too.

**Comment by hacksparrow** [comment]
@tunniclm the font on the website is Helvetica :)

Ok, so based on the feedback on lowercase e, I am uploading two more variants. This time, no more Helvetica; it is a handcrafted "font".

**Comment by hacksparrow** [comment]
**ex**

![expressjs-logo-ex-512](https://cloud.githubusercontent.com/assets/950112/14080740/8f92037a-f524-11e5-8c52-27a9ac63af50.png)
![expressjs-logo-ex-256](https://cloud.githubusercontent.com/assets/950112/14080744/9234d53a-f524-11e5-99d5-7b9b145fab88.png)
![expressjs-logo-ex-128](https://cloud.githubusercontent.com/assets/950112/14080746/939ac0ec-f524-11e5-8c05-a148d6f64b51.png)

**Speeding "e"**

![expressjs-logo-speeding-512](https://cloud.githubusercontent.com/assets/950112/14080753/9ecb8ca8-f524-11e5-9e44-0158deae74ed.png)
![expressjs-logo-speeding-256](https://cloud.githubusercontent.com/assets/950112/14080755/a0245de6-f524-11e5-9d6b-0ddbb90a59d1.png)
![expressjs-logo-speeding-128](https://cloud.githubusercontent.com/assets/950112/14080756/a29d20d0-f524-11e5-8979-65cf210b674e.png)

**Comment by dougwilson** [comment]
I think the "speeding e" looks too similar to the Internet Explorer logo, as just looking at it instantly reminded me of IE.

**Comment by hacksparrow** [comment]
Agreed. The IE logo has become a part of our psyche; any large size, even-looking, fat **e** hints of IE.

Back to the drawing board.

**Comment by julianlam** [comment]
Am I allowed to comment? 

Capital E in Ex brings to mind the FedEx logo. Lowercase seems superior in my opinion

**Comment by hacksparrow** [comment]
@julianlam this discussion is open to all.

Thanks for your feedback. Designing the Express logo is gonna be a tough one, for sure 😁

**Comment by crandmck** [comment]
BTW, @hacksparrow added a temporary favicon for http://expressjs.com/ (using lowercase "e").   
I don't think its necessarily permanent, but it's a "working" icon for the time being.

**Comment by lordKnighton** [comment]
+1 `@tunniclm`  lower case ex

**Comment by crandmck** [comment]
In discussion during TC meeting (see #9) the general feeling was that the favicon was "good enough" for now. The main purpose is just to identify the site on the browser tab/window, and it does that.  If anyone has a specific suggestion for something better, then they can open a new issue.

Thanks again to @hacksparrow for adding the current favicon.
