### ISSUE TITLE
Triage Meeting  05-07-2020

### ISSUE THREAD

**Issue by jonchurch** [expressjs/discussions#123]
@ghinks and I were discussing having a triage meeting the day after the next TC meeting. 

The goal would be to bring up any triage topics that folks want to discuss, and also to onboard a few new members.

Invited:

Open to whomever wants to attend.

* @expressjs/express-tc (if interested)
* @expressjs/triagers

## When
May 6, 2020 - [24:00 UTC](https://www.google.com/search?q=24%3A00+UTC)

Expected length, no more than 1 hour.

## Where

Zoom, link TBA

## Agenda

* Onboard some new members
* Suggest an agenda item with a comment here

**Comment by jonchurch** [comment]
This date/time is flexible if folks aren't able to attend. If you'd like to suggest an alternate day/time please do speak up.

**Comment by lekanikotun** [comment]
Hi,

Proposed date and time works for me.

**Comment by ryhinchey** [comment]
Date works for me but 7:30pm ET can be tough as it’s right at bed time for my young ones.

**Comment by jonchurch** [comment]
@ryhinchey is 8pm ET a move in the right direction?

**Comment by ryhinchey** [comment]
@jonchurch It is but If 7:30 is the preferred time I can either try my best to join or provide thoughts to agenda items ahead of time

**Comment by wesleytodd** [comment]
I would be happy to attend as an observer!  If you want I can also make the zoom link on the OpenJS account.

**Comment by ghinks** [comment]
I am good with either 7:30 or 8:00PM EST for Thurs 7th May
I am going to check with the prospective new **triage** members now.

**Comment by e-l-i-s-e** [comment]
7:30 or 8:00 also works for me (a prospective triage member).

**Comment by jonchurch** [comment]
I'm fine moving it to 8pm, and I don't see any nays on that. Will be watching this today and tmr, but let's plan on 8pm.

**Comment by jonchurch** [comment]
@wesleytodd I don't have permissions for zoom, and don't have a paid account. If you're able to attend and host w/ zoom, great!

**Comment by bryan-a-costa** [comment]
May 7th at 8pm EST works for me (prospective new triage member as well).

**Comment by Magdalena-A** [comment]
I'm another prospective new triage member and would like to join tomorrow at 8pm as well.

**Comment by DT455** [comment]
Hello, I am interested in helping with triage as well.  I'll plan to join tomorrow at 8.

**Comment by mastermatt** [comment]
I plan on attending as well.

**Comment by ghinks** [comment]
Glenn Hinks is inviting you to a scheduled Zoom meeting.

Join Zoom Meeting
https://us04web.zoom.us/j/77174537859

Meeting ID: 771 7453 7859
One tap mobile
+13017158592,,77174537859# US (Germantown)
+13126266799,,77174537859# US (Chicago)

Dial by your location
        +1 301 715 8592 US (Germantown)
        +1 312 626 6799 US (Chicago)
        +1 929 205 6099 US (New York)
        +1 253 215 8782 US (Tacoma)
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
Meeting ID: 771 7453 7859
Find your local number: https://us04web.zoom.us/u/fb5iOjWE4r

**Comment by jonchurch** [comment]
Here's [the PR](https://github.com/expressjs/express/pull/4211/files) that outlines how to apply for Triage

**Comment by jonchurch** [comment]
Here's [my notes](https://docs.google.com/document/d/1hvaWW-bCDISHbpoIy4s_57Ci8u5gKjpI3Y1Kex_8WIw/edit?usp=sharing) I was reading from during the meeting.

Once you are on the triage team, you can post to the [team discussions here](https://github.com/orgs/expressjs/teams/triagers), feel free to introduce yourself and ask any questions!

My list of tips and tricks, which covers subscribing to all the repos, [is here](https://github.com/orgs/expressjs/teams/triagers/discussions/5). If you can't see that link yet, here it is [in gist form](https://gist.github.com/jonchurch/80f0a01dd79e656e64f2e750995d1d35).

If you're still feeling lost and confused, don't panic! No one expects folks to be productive immediately after joining, and we will hopefully figure out together how any of this actually works :heart:

**Comment by ghinks** [comment]
# attendees

- Glenn Hinks
- Jonathan Church
- Ryan Hinchey
- Matt Wilson
- Dave Taylor
- David Ashe
- Elise Bonner 
- Magdalena Aichinger

We held general discussions on the roles of the triage team members.

A text transcript is here.

[express triagers meeting 20200507_otter.ai.txt](https://github.com/expressjs/discussions/files/4601332/express.triagers.meeting.20200507_otter.ai.txt)

**Comment by lekanikotun** [comment]
> # attendees
> * Glenn Hinks
> * Jonathan Church
> * Ryan Hinchey
> * Matt Wilson
> * Dave Taylor
> * David Ashe
> * Elise Bonner
> * Magdalena Aichinger
> 
> We held general discussions on the roles of the triage team members.
> 
> A text transcript is here.
> 
> [express triagers meeting 20200507_otter.ai.txt](https://github.com/expressjs/discussions/files/4601332/express.triagers.meeting.20200507_otter.ai.txt)

@ghinks you left my name out from the list of attendees.

**Comment by jonchurch** [comment]
Hey there folks! I wanted to remind ya'll to request a Triage role if you're still interested. There's zero pressure, if you decide later it's not for you, you can always bow out or ask to be removed. Requesting to join is done by opening an issue, [see here](https://github.com/expressjs/express/blob/master/Contributing.md#becoming-a-triager) for more information.

I know our onboarding meeting was quite a download, and it was certainly rough around the edges (this was the first time we'd ever done something like this). If anyone has critical feedback about your experience in the meeting (especially if it's about me dominating air time!) we'd be happy to hear it, either here, or if you're more comfortable privately via email. My email is on my profile, as is @ghinks. 

I'm going to open a new issue proposing another Triage meeting for May 21st. Details can be hashed out there, but I'm assuming it will be a much more informal session group discussion driven by attendees or maybe we do some triage together as a learning experience. ❤️

**Comment by jonchurch** [comment]
Actually, going to keep this open a little longer so it's easier to find for folks who aren't yet plugged into this repo.

**Comment by dougwilson** [comment]
This meeting is now up on the YouTube account: https://youtu.be/v0sGchM6Hmc
Additionally, I have created a playlist for the two meeting types, triage: https://www.youtube.com/playlist?list=PLZWsMwozdu4y5zUt2b7JOGNnASUvZZsso
