### ISSUE TITLE
Triage Meeting 05-21-2020

### ISSUE THREAD

**Issue by jonchurch** [expressjs/discussions#125]
### Invited:

Open to the whole community, folks who are triagers now, would like to become one, or who just want to watch.

* @expressjs/express-tc (if interested)
* @expressjs/triagers

## When
May 21, 2020 - [24:00 UTC](https://www.google.com/search?q=24%3A00+UTC)

Expected length, no more than 1 hour.

## Where

Zoom, link TBA

## Agenda

* Check in w/ current Triagers and see how they're feeling
* Suggest an agenda item with a comment here

If you plan to attend, drop a 👍 reaction, if you don't plan to drop a 👎 , if undecided use a ❓

**Comment by jonchurch** [comment]
Hey yall, proposing another Triage meeting. 8pm Eastern seemed to work well last time, so I've proposed that time again.

These meetings are still very new, and I'd love to see us discuss what folks want to get out of them. Feel free to add your thoughts, or propose an agenda item.

If you're able to attend, drop a comment (so you'll get notifications here if you aren't already subscribed) and/or add a reaction to the top level comment.

**Comment by ryhinchey** [comment]
I think triaging a few issues might be helpful for the new triagers.  I’d be happy to go over a few open issues or review recently closed ones.  

To the new triagers joining - if you’ve looked at any issues you’d like to discuss / triage, feel free to bring those 😁

**Comment by jonchurch** [comment]
Possible Agenda Item: Labels, what are we missing? What do the ones we have mean? Where can we codify that?

**Comment by ghinks** [comment]
Glenn Hinks is inviting you to a scheduled Zoom meeting.

Join Zoom Meeting
https://us02web.zoom.us/j/83631407014?pwd=R3Q1SjhCTjBLUlBmb3E5d0I3dFIrUT09

Meeting ID: 836 3140 7014
Password: 487762
One tap mobile
+19292056099,,83631407014#,,1#,487762# US (New York)
+13017158592,,83631407014#,,1#,487762# US (Germantown)

Dial by your location
        +1 929 205 6099 US (New York)
        +1 301 715 8592 US (Germantown)
        +1 312 626 6799 US (Chicago)
        +1 669 900 6833 US (San Jose)
        +1 253 215 8782 US (Tacoma)
        +1 346 248 7799 US (Houston)
Meeting ID: 836 3140 7014
Password: 487762
Find your local number: https://us02web.zoom.us/u/kdNjwO7wAo

**Comment by jonchurch** [comment]
Beginning of issue templates https://github.com/expressjs/.github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by jonchurch** [comment]
Highly recommend watching Wes' talk about Express https://www.youtube.com/watch?v=HxGt_3F0ULg

**Comment by jonchurch** [comment]
@ryhinchey here is that chrome extension I mentioned https://chrome.google.com/webstore/detail/octolinker/jlmafbaeoofdegohdhinkhilhclaklkp?hl=en

**Comment by gireeshpunathil** [comment]
closing as completed, feel free to re-open if there are pending items
