### ISSUE TITLE
Confusing module on npm "express5"

### ISSUE THREAD

**Issue by dougwilson** [expressjs/discussions#13]
I just was made aware of a module that has been published to npm a while ago with a confusing name: https://www.npmjs.com/package/express5

It looks like a user published the first alpha of 5.0 under the package name `express5`, which may likely be confusing to users. I'm not sure if we need to do anything or not, which is why I'm posting here.

The weird part is that it was published earlier this year, yet the second 5.0 alpha was out mid last year, so it doesn't seem like whoever that is is even trying to keep it up-to-date.

There is apparently an `express3` and `express4` package as well. `¯\_(ツ)_/¯`

/cc @expressjs/express-tc  @mikeal @jasnell

**Comment by jasnell** [comment]
There's likely not anything to do other than to keep moving forward on the
real v5.

**Comment by LinusU** [comment]
The npm team has shown that they see keeping the community at large happy and as little confused as possible as a priority. I think it might be a good idea to reach out to them and see what they have to say.

I personally would like them removed as they could potentially be confusing to our users...

**Comment by gabeio** [comment]
If they are not kept up to date this definitely could be a pain figuring out if users are using our version or the version provided by the alternative packages.

This could potentially be a security hazard as we do not know if these modules have been modified or compromised. Not to say that users can't take our code and modify it but that it really shouldn't be published *as* us.

**Comment by koistya** [comment]
> There's likely not anything to do other than to keep moving forward on the real v5.

Yep, exactly. I just have removed this package from NPM to avoid confusion.

**Comment by hacksparrow** [comment]
@koistya that's cool of you. Thanks.

**Comment by Fishrock123** [comment]
sounds like this got resolved.
