### ISSUE TITLE
Realtime communication channel

### ISSUE THREAD

**Issue by dougwilson** [expressjs/discussions#130]
I am opening this just as a general issue to get a feeling for what both the TC and the fuller collaborators feel about this: are we interested in having some kind of project-wide "realtime communication channel", either private to the collaborators, or public for the entire community. An example for a "realtime communication channel" would be Slack or similar.

We of course have GitHub, and a few of our meetings, and the idea for this is not to really replace something that exists already, but perhaps to augment. I am spurred for the idea as we continue to expand, especially with the triage members.

**Comment by jonchurch** [comment]
That could be cool. Discord maybe? I know that having another app can be a pain, but I personally like the voice channels they have. You can hop in and out of a voice channel seamlessly, without having to start or accept a call. You can also screenshare into the channel easily as well. 

I'd be open to Slack as well, though.

**Comment by gireeshpunathil** [comment]
+1 to slack. open to discord too.

**Comment by wesleytodd** [comment]
My only concern about discord is that I am in some video game channels and get tons of notifications, so tend to ignore them.  Slack also has the benefit for some of being typically open on work computers.  This is one reason I am so often in the tools, noders, and open js slacks.

**Comment by minnaliang** [comment]
+1 for slack!

**Comment by ghinks** [comment]
I am neutral on the two options being talked about. However we should use the method of communications that the next generation of maintainers would use. Which may not be slack 😆

**Comment by jonchurch** [comment]
Assuming its mostly a small group of folks, I think Slack will be fine. I also definitely have slack open during work

**Comment by wesleytodd** [comment]
I think we already have that but in the Node Slackers channel.  I do think we should preference the OpenJs resource though, because it is a paid account.

**Comment by FAXES** [comment]
+1 discord, would love to get to know some fellow expressors :D

**Comment by filipkappa** [comment]
What's the status of this? Is there a plan to create a slack / discord channel?

**Comment by UlisesGascon** [comment]
I think that we can use the channel `#express` o create a new one like `#express-core` in the OpenJS Foundation Slack. There is a good moderation team in place. We can access from this link: https://openjsf.org/collaboration/. 

We won't need any resource or cost to keep this infra running :).

**Comment by IamLizu** [comment]
Closing this as we have already moved to Slack for real-time communication and it can be accessed via the above posted link by UlisesGascon.
