### ISSUE TITLE
nomination for express committer

### ISSUE THREAD

**Issue by gireeshpunathil** [expressjs/discussions#131]
I would like to propose Jonathan Church (@jonchurch) as an express committer. It is not clear from the contributing guide as to i) who can nominate, ii) whether the nominee's prior consent be sought so I am taking the liberty here.

Non-trivial contributions:

PRs: https://github.com/pulls?q=is%3Apr+author%3Ajonchurch+org%3Aexpressjs+
Involvements: https://github.com/issues?q=involves%3Ajonchurch+org%3Aexpressjs+
Substantial contributions and leadership to express triage efforts
Substantial contributions to project process automation
Help driving express 5.0 efforts
Help driving express evangelism, adoption and user experience

**Comment by dougwilson** [comment]
So there isn't a specific nomination process outlined, as we haven't gone through it enough to say what one would be, and the foundation's guidance for term didn't include one, either :) The guidance from the foundation was just that those who lead the projects would automatically recognize those who are contributing and who want to become committers and do so, so thus nominations for a committer is not currently a thing. @jonchurch has already expressed and we're looking into elevating to committer on the expressjs.com repo.

From our last meeting we talked about how to grow and set out from that meeting to create a method to actually elevate folks to a committer on a repo-by-repo basis. I believe @wesleytodd volunteered to create all the teams and such to help make this happen, but I don't think anything has happened just yet on that front. Once we get that set up, there is already plans to get both Jon & Glenn added as committers to the repos we have spoken about amongst the group 👍

**Comment by dougwilson** [comment]
I created #132 for a tracking issue for that discussion item in the TC meeting, which was needed in order to perform the elevation.

**Comment by gireeshpunathil** [comment]
this is a great news!
