### ISSUE TITLE
Delete jshttp/compress repo

### ISSUE THREAD

**Issue by mastermatt** [expressjs/discussions#133]
This is a proposal to delete the https://github.com/jshttp/compress repo. 

While digging around older, unanswered/unlabeled issues, I came across https://github.com/jshttp/compress/issues/1, which lead me to the repo with no code in it. 

Unless it has a purpose, can we delete it for general housekeeping?

**Comment by dougwilson** [comment]
A completely empty repo is certainly useless. It had plans several years ago but no work done. Because it is empty with no prs, wiki, projects, or issues, I deleted it, as it can always be recreated and it will still be the same at that time with nothing lost.
