### ISSUE TITLE
2016-04-27 TC Meeting missing?

### ISSUE THREAD

**Issue by LinusU** [expressjs/discussions#15]
ping @dougwilson **crandmck**, is there going to be a meeting today? I don't see any issue opened about it?

**Comment by dougwilson** [comment]
No, they are every two weeks :)

**Comment by LinusU** [comment]
...and that explains it. Thanks for the quick answer, saved me from staying up all night for nothing :)

Sorry for the unnecessary ping, see you next week 👋

**Comment by dougwilson** [comment]
I went ahead and created the placeholder for next week :) It's A-OK for the ping, especially if you were trying to decide your sleep schedule :D
