### ISSUE TITLE
Is this discussions board still active or dead?

### ISSUE THREAD

**Issue by filipkappa** [expressjs/discussions#156]
Since GitHub now allows the discussions to be added directly to the repository, and express has its own discussions tab - should this repo still be linked as a primary community directory on the [Express JS site](https://expressjs.com/en/resources/community.html)?

**Comment by dougwilson** [comment]
Good point. We do have discussions enabled on the express repo, but that is more for general discussions for help and stuff, while this is still used foe the purposes listed on that page. They are kept separate on purpose 👍
