### ISSUE TITLE
Routing bug - URIError: Failed to decode param '$%^'

### ISSUE THREAD

**Issue by debuger001** [expressjs/discussions#159]
Hi There,

I have found this weird bug in routing. Any API route param if contains these 3 characters in this sequence "**$%^**" it breaks the router and crashed. I need help how to prevent this from happening.

`URIError: Failed to decode param &#39;12321$%^4ABCD&#39;<br> &nbsp; &nbsp;at decodeURIComponent (&lt;anonymous&gt;)`

**Express Route:**
![express_route](https://github.com/expressjs/discussions/assets/62402545/cc4a2f06-5fd9-416a-b711-e30d77ba72c7)

**Valid Call**
![express_route_valid_call](https://github.com/expressjs/discussions/assets/62402545/4b3bd0fd-6f14-44d5-a02c-feccea72be18)

**Invalid Call**
![express_route_invalid_call](https://github.com/expressjs/discussions/assets/62402545/19484b30-8f29-4102-ab4d-2c2af4083be4)

**Comment by dougwilson** [comment]
Hello, think is working as intended. Your app doesn't crash, express is just replying with a 400 bad request. In http urls, there are various characters that have special meanings. In this case it is the `%` character as it is expected to be part of an encoded sequence (should be followed by two hex digits). If you want to send a literal `%`, the url should instead contain `$%25^`. I hope this helps!
