### ISSUE TITLE
EFI: New Technical Committee

### ISSUE THREAD

**Issue by sheplu** [expressjs/discussions#168]
### Motivation

The Technical Committee is the core group of the project, responsible for all actions and the Express organizations on part with other large Open Source Project. 
Without this core group of people, the project is at risk and some critical decision cannot be validated. By having a sufficiently large group of people, it is certains that in a 2-4 weeks timeline decisions can be validated and acted on.

### Expectation

Reform a full TC and do all the setup required leading to a global success.

### Implementation 

Update contribution
Update website
Announcement 
Setup access (Github, Social, SaaS if any...)
Setup a new regular meeting for the TC

### Status
Part: Organization
Status: 
- contribution update: [done](https://github.com/expressjs/express/pull/5483)
- update website: [done](https://github.com/expressjs/expressjs.com/pull/1460) [done](https://github.com/expressjs/expressjs.com/pull/1461)
- announcement: [done](https://twitter.com/UseExpressJS/status/1758300852870381931)
- setup access: done for GitHub
- setup meeting: [in progress](https://github.com/expressjs/discussions/issues/195)

### Draft

> The Technical Committee (TC)  is the core group of the project, responsible for all actions and guaranteeing a bright future for Express.
Reforming an active TC

**Comment by wesleytodd** [comment]
https://github.com/expressjs/express/pull/5483

That landed. I was thinking we need to consolidate the charter and contributing docs, did we have any more planed changes? Do we need this one still?

**Comment by sheplu** [comment]
Updated this one with all the points, I think we are covered and we can close it.
The only missing point is the recurring meeting, but the issue is open, so I think we are covered here

If there is no objection I am closing that this weekend, giving a few days for people in the @expressjs/express-tc to comment

**Comment by UlisesGascon** [comment]
Great consolidation, @sheplu! 

One comment on setup access, the expected outcome is to grant access for all the TC members to all the repos in the orgs (I assume as owners?) and also to the NPM publication?

**Comment by wesleytodd** [comment]
I guess we maybe do still want to call this incomplete until we get the npm stuff sorted. I think @dougwilson added Kylie to the youtube (and myself), but we do need to get a plan documented for managing that going forward as well. I guess the idea is, like the other things, any TC member should be able to manage it to make sure have no bottlenecks on getting things done.

**Comment by wesleytodd** [comment]
The npm stuff is sorted out and the first release went out. I say we call this one complete.
