### ISSUE TITLE
EFI: Define Technical Committee role

### ISSUE THREAD

**Issue by sheplu** [expressjs/discussions#169]
### Motivation

Now that the TC is formed, it is important to setup all the mains roles for success. It means having a clear definition and understanding of each roles part of the project. By having a clear document, it will be easier to know how and when contributor can apply (or be selected) to be a captain, how new Working Groups can emerge...

### Expectation

Charter for the TC and specific part for processes that could involve the TC, for example nominating new TC members, appointing a Captain or creating a Working Group.
This would also include role of the TC at a more global scope, for example CPC representation

### Implementation

Define / update role of the TC
Create / update role of the Captains - and delegation from the TC
Define / update role of a Working Group (if needed) - and delegation from the TC

As part of the TC
- Define how / when a breaking change can be introduced (or delegated to captains / WG?)
- Represente the project in the CPC (capability to vote / be elected)

### Status

Part: Organization
Status:

### Draft

> An active TC is primordial if we want the project to be successful. The role of the TC is to oversee the reach and technical challenges of the project, while taking part in all organization issues. We need to define and refine the role and capabilities of the TC.
This can include role as 
Changing operational roles and creating specific role (as captains)
Delegating some tasks and decisions to a specific Working Group
Represent to project in cross project sessions
Choosing to add or remove core feature with huge impact
…

**Comment by wesleytodd** [comment]
Similar to #168, I think we have covered these. We should double check that we didn't miss anything but then likely close these ones.

**Comment by jonchurch** [comment]
I don't think we've completed:

> Charter for the TC and specific part for processes that could involve the TC

Im opening a Draft PR to start that which I welcome/request input and pushes directly to. leaving sections "intentionally blank" bc I do not have an answer for them on my own.

https://github.com/expressjs/express/pull/5509

**Comment by wesleytodd** [comment]
With @jonchurch's PR and the other additions we have made I think this is nearing complete. I think to clear on where the conversation should happen I think we should not have issues hanging around once the main work has started. I am going to close this one calling it complete pending landing that PR in the admin repo.
