### ISSUE TITLE
Share the load doug!

### ISSUE THREAD

**Issue by jonathanong** [expressjs/discussions#20]
thanks for all your work @dougwilson. i haven't been really involved in express for a while, but i'd still like to help. let me know how i or anyone else can help:
- bump dependencies
- convert to standard
- documentation

etc.

i know you are particular on how you do things, so it would be great if you wrote it down :) i'll be sure not to publish myself so i don't mess it up ;)

**Comment by dougwilson** [comment]
All those topics sound good! I think that I can get some documentation put together on this stuff. And I think one thing we can talk about tomorrow is a good way to understand what is happening around the repos (that would be more towards point 3).

**Comment by gabeio** [comment]
I just created a pr for the session module to convert it to the standard 👍 

there are a few errors that standard spits out that I don't know how to fix.

**Comment by tunniclm** [comment]
Regarding documenting process, I would welcome comments on this PR to make it more accurate and informative: https://github.com/expressjs/express/pull/2890
