### ISSUE TITLE
How can I update the session with data from the database

### ISSUE THREAD

**Issue by TheDogHusky** [expressjs/discussions#204]
Hey.

I am working for a friend and making him a website with a dashboard and discord account connexion.
I am recently facing a problem in the writing of the code: I have no idea how can I make this work, let me explain.

I have a /login route which redirects to the discord page. 
Then discord redirectsto /login with the code (the OAuth2 code), which handles it, gets the access token and user information and it all to the session using session.save() after updating the properties as well as creating or getting a DB entry so I can have the data associated with the Discord account (for example: the staffLevel (used for the dashboard), website roles, etc..).
But now I face a problem: how can I update the session at each request in a correct and optimized way to get the database data?
Because if someone updates the data on the dashboard (eg: disables his account, changes the staffLevel), I need it to be accessible so I can deal with these changes. 
I might be unclear, and I'm sorry for that, the ideas are not clear in my head too, don't hesitate to ask for more details.

I guess for now some sort of middleware that does session.reload() could work, with then a token validity check, but I know that mine won't be optimized and that's why I'm asking y'all how can I make that secure and optimized.

For the database I use a MongoDB Atlas with Mongoose for the backend. Also I don't think storing the avatarURL, the username and other things could be useful in the database as it is already stored in the session.

So any ideas?

**Comment by wesleytodd** [comment]
Hey @TheDogHusky, this repo is more about discussions as related to the project. Like planning, governance, and things like that. If you have a bug with the session package, or need help figuring something out, I would suggest posting in that repo. That said, we don't provide tech support for the project, so you might have better luck with this on StackOverflow or Reddit where folks in the community often volunteer their time to help with questions like this.
