### ISSUE TITLE
Wayward Packages not under Express umbrella orgs

### ISSUE THREAD

**Issue by jonchurch** [expressjs/discussions#212]
Just noticed that [`escape-html`](https://github.com/component/escape-html) lives in a different github org than any other packages.

That is obvious from my list of [direct express deps and their github orgs](https://gist.github.com/jonchurch/29fd6f13e99ae0ea238b674b3d9e3e26), but I just noticed when reading some issues. 

Im wondering if there are any others like this which are transitive deps, packages maintained by doug or other express contribs for their use in express itself or `jshttp` or `pillarjs` but are not in one of the orgs. I have that list of direct deps of express, so we know the status of directs, but its possible such a situation exists for some transitive.

To be clear, Im asking if there are any packages which seem like they _should_ be in the orgs but are not through maybe overlook or some history which may not be relevant now. I think `escape-html` is one such example.

We should figure this out. A fun but manual way to check this is to visualize the express package dep tree.

https://npmgraph.js.org/?q=express#select=exact%3Aescape-html%401.0.3

![Screenshot 2024-03-10 at 7 25 35 PM](https://github.com/expressjs/discussions/assets/12915163/b0972852-69dd-4dbe-9813-f94e55c89aa5)

**Comment by dougwilson** [comment]
The escape-html package doesn't belong to OpenJS or Express.Js on purpose, which is why it is not part of the three organizations. It is not an oversight.

**Comment by dougwilson** [comment]
It is no different than how the qs package does not belong to the Express.js organization, as an example :)

**Comment by jonchurch** [comment]
@dougwilson what kind of access do you have on the repo/org? I think you're the only person with npm publish rights on the package.

Regardless of the answer it is indeed the same relationship we have with `qs`. The only thing that stands out between them to me is that you're not publicly listed as a member of the org or identified as the maintainer of the repo. Compared to the clear relationship of who owns `qs`. I don't know the history of the package or the component org, so it looks at first glance like an express affiliated package.

Apparently it is not a mistake, and so I'd be willing to assume there are no wayward packages and things are where they are meant to be.

**Comment by dougwilson** [comment]
I am an admin of the org and work on the package with any other member of thay org, just as how the express orgs work.

**Comment by jonchurch** [comment]
Great that's what I expected. I know that not all a user's orgs are publicly displayed. Thanks for clarifying
