### ISSUE TITLE
Express TC meeting 2016-07-13 [canceled]

### ISSUE THREAD

**Issue by crandmck** [expressjs/discussions#24]
I'm just adding this since Doug hasn't done so yet....
## Who

The entire community is welcome to tune in and observe the meeting live at the time below. The following people are listed here as explicit invitees to get an email notification about the upcoming meeting:

Invited: 
- @expressjs/express-tc 
- @mikeal (tsc mentor)
- @jasnell (tsc mentor) 
- @wesleytodd (observer)
- @tunniclm (observer)
- @sjanuary (observer)
- @ritch (observer)
- @gabeio (observer)
## When

July 13, 2016 - [23:30 UTC ](https://www.google.com/search?q=23%3A30+UTC&oq=23%3A30+UTC)
## Where

Google Hangouts: TBD

Link for Participants: TBD
## Agenda
- I added a para. about TC in two places on the website.
- Adding list of TC members to website https://github.com/expressjs/expressjs.com/pull/673
- CloudFlare?
- Other

**Comment by crandmck** [comment]
I'm assuming Doug will add links to hangout above ^..

**Comment by crandmck** [comment]
@dougwilson - Are we going to have a TC meeting today?
Is anyone else interested in joining?

**Comment by crandmck** [comment]
OK since no one has commented, I'm assuming this meeting is canceled.

**Comment by cdnadmin** [comment]
Bummer.  😞 

For those of us that scan/filter on the `meeting` label, can we please add it to this issue too, for the sake of thoroughness, while some of us quickly get ourselves up to date as to what's going on?  :-)

Thx.

**Comment by crandmck** [comment]
@cdnadmin Sure, sorry 'bout that.  Will do.

**Comment by gireeshpunathil** [comment]
meeting happened long back, closing. Please re-open if anything is outstanding here.
