### ISSUE TITLE
Sustainability Program: HeroDevs (Coordination)

### ISSUE THREAD

**Issue by UlisesGascon** [expressjs/discussions#257]
I created this issue to follow up on the pending tasks for coordination between us. Related https://github.com/expressjs/discussions/issues/228#issuecomment-2059216751

**Pending tasks**
- [ ] Create an Open Collective account (@sheplu)
- [ ] propose and get approval for adjustments/links added to the express site (@joeeames / @expressjs/express-tc )
- [ ] submit a PR after that approval (@UlisesGascon )
- [ ] Public the LTS Plan: discuss, decide and execute any necessary issue creations/deprecations of npm versions (@expressjs/express-tc )

**Important**
Note: I will edit this issue and add more details soon.

**Comment by wesleytodd** [comment]
I tried to make one for my Express OpenAPI lib just to get a feel for it but they said things have to be owned by an org to start an OC for it. So I would love if we could get this shared account setup soon just so we are ready and can all log in to check things out and make sure we get any questions answered in advance.

**Comment by joeeames** [comment]
@UlisesGascon I just want to confirm, this is to coordinate all tasks for Express participation in the ESP yes?

If so, I believe we have the following tasks:
1) propose and get approval for adjustments/links added to the express site
2) submit a PR after that approval
3) discuss, decide and execute any necessary issue creations/deprecations of npm versions

Is that right?

**Comment by UlisesGascon** [comment]
Yeah! I added them to the TODO list @joeeames :+1:

**Comment by UlisesGascon** [comment]
This issue can be closed now, as https://expressjs.com/2024/10/01/HeroDevs-partnership-announcement.html when public already :partying_face:
