### ISSUE TITLE
link redirect after IP address change

### ISSUE THREAD

**Issue by KarthickVenkatesh** [expressjs/discussions#28]
Hi,
I'm running node server on some IP say 192.168.xx.xx
I have a module in my application where i can change the IP address.
Now when i change the IP to say 192.168.yy.yy, then i wait for 30 sec for the change to take effect & redirect the link to 192.168.yy.yy it doesn't happen.

Can anyone say where the problem lies?

**Comment by hacksparrow** [comment]
Best to ask at https://gitter.im/nodejs/node. If you are using Express, ask at https://gitter.im/expressjs/express.
