### ISSUE TITLE
node 0.8

### ISSUE THREAD

**Issue by jonathanong** [expressjs/discussions#3]
we still supporting this @dougwilson? https://github.com/pillarjs/resolve-path is starting to fail on 0.8. i think we can ditch it now...

**Comment by dougwilson** [comment]
We absolutely are. The Travis CI needs to be fixed. May have wanted to ask before breaking the build (or looking at the other repositories).

**Comment by jonathanong** [comment]
alright. let me know how to proceed. i could fix this on travis but not sure how this would differ on appveyor

**Comment by dougwilson** [comment]
Also, why was the version bumped patch instead of minor? The dependency update is providing a new feature, which is directly visible in that module's interface, so it should be a minor version bump to represent that there is a new feature available.

**Comment by dougwilson** [comment]
Ignoring the questionable adherence to semver on what was published, it should at least be reasonable to wait for all-green the the CIs on the commit that is going to be published before publishing. I'm rebasing your changes on my commits from earlier this year that resolves the CI configurations for the istanbul module misbehaving.

**Comment by dougwilson** [comment]
Builds should be resolved in `resolve-path` now.

**Comment by dougwilson** [comment]
Oh, and I guess on the Node.js 0.8 topic over-all, yes, Node.js 0.8 can be removed from the testing, but the module will need to undergo a major version bump at the same time to be fair to the users who are depending on the modules working.
