### ISSUE TITLE
Move in multiparty

### ISSUE THREAD

**Issue by dougwilson** [expressjs/discussions#30]
This is an issue to discuss if we want to move the `multiparty` module into the Express.js TC (probably under the `pillarjs` organization). I know I personally use it a lot, and have had a bunch of work go in there, but want to get how people feel about this. The module is currently offered to me if I would like to move it, and I feel like, if anywhere, Express.js would be a fine home for it.

**Comment by crandmck** [comment]
Just to be clear, you're referring to https://github.com/andrewrk/node-multiparty, right?

**Comment by dougwilson** [comment]
Yes

**Comment by dougwilson** [comment]
I'm going to add @andrewrk as an owner to the `expressjs` organization in GitHub so he can move the https://github.com/andrewrk/node-multiparty and https://github.com/andrewrk/connect-multiparty repositories into the organization. After the move, I will downgrade the membership to a member of a multiparty team and then we can figure it out from there :)

**Comment by andrewrk** [comment]
Sounds good. Let me know when it's time for me to take action.

**Comment by andrewrk** [comment]
Alright, both repos transferred

**Comment by dougwilson** [comment]
Awesome, @andrewrk !
