### ISSUE TITLE
Proposal to create more distinctive branding and logo

### ISSUE THREAD

**Issue by crandmck** [expressjs/discussions#31]
@RoyalRajdeep proposed in https://github.com/expressjs/expressjs.com/pull/684#issuecomment-239383393

>Each Library and Framework I use, Have their own Branding, Iconic Logos, and Color theme, But Express is still not having any specific color theme, Iconic brand Logo. We are just having a simple b/w color themed website and a very simple logo type.

> If Express Js community have the same thought , then I go ahead for this part to 
1. Suggest a new color theme for all Express Js related stuff. (Like NodeJS has Green+Grey, and they use the same Color Combination on all their stuff, Angular has Pink+White.)
2. Design a new logo for express, based on our community suggestions.

This would be something that the @expressjs/express-tc would need to approve and perhaps discuss, so that's why I created this issue.

> For the Website Part I will made a proposal soon.

@RoyalRajdeep please open a separate issue for any other proposal.

**Comment by dougwilson** [comment]
Express has branding, colors, etc. Sure, they are plain, but I think they exist. It almost sounds like the proposal is saying that what we have is just not liked by the user? What is wrong with the current colors and the logo being the word "express", etc.?

**Comment by dougwilson** [comment]
If any logo is created, we need to understand who would own the copyright, make sure anything about it is explicit, probably register US trademarks to protect the branding (and to prevent trolls), etc.

**Comment by crandmck** [comment]
+1 @dougwilson 
Re point no. 1, I'd also like to know what's wrong with the current branding/logo.  I agree that what we have is "minimal, but workable". More to the point @RoyalRajdeep if you have something in mind, I think we're open to seeing it, but I think it would have to be a marked improvement to consider changing the site.  Nevertheless, I didn't want to dismiss the proposal out of hand.

Re point no. 2, any work that's done should be with the explicit understanding that all rights to it (logo, etc) will be assigned to the Node Foundation...I assume that's the right owner(?)  

I don't know if we can get the "Express" trademark--I recall some discussion about this and that it wasn't possible for some reason... but I don't recall the specifics.

**Comment by dougwilson** [comment]
So the trademark for the logo itself, not necessarily the word, as I believe those are different things :)

Regardless, I agree with your statement, that we are open to hear any proposals :) I just wanted to make sure there was an understanding that, imo, it's not that we have nothing, but rather someone just thinks it can be "better" in some regard :)

Basically to say that if said person were to go and work a lot and create an entirely new branding, there is no guarantee of acceptance, but at the same time, we are not outright rejecting the idea, though understanding something more concrete would certainly help :)

**Comment by dougwilson** [comment]
Some may say that having a minimalistic branding is a reflection of the minimalistic nature of express :)

**Comment by crandmck** [comment]
Unless someone has more input on this, I suggest we close this out.  Anyway, I don't think it's a high priority, and there didn't seem to be a strong consensus that anything more is needed beyond what we have now.

**Comment by hacksparrow** [comment]
+1 for closing.

**Comment by dougwilson** [comment]
_closing_
