### ISSUE TITLE
Establish README Guidelines / Standard

### ISSUE THREAD

**Issue by crandmck** [expressjs/discussions#33]
Per TC discussion in (see #32), we'd like to have some general standards for README organization, content, style, and formatting.  Let's discuss here.

**Comment by crandmck** [comment]
Here's my initial proposal for discussion: https://github.com/expressjs/expressjs.com/wiki/Proposed-README-Guidelines-and-Template.
Hopefully, it's not too much...

A few sections have comments labeled "For discussion".

I believe in the TC meeting, @dougwilson mentioned some other README spec/template, but I don't recall the specifics.  If you want to link to it for comparison, we can fold that into the discussion.

**Comment by dougwilson** [comment]
Awesome write up, @crandmck! I'll take a look over the weekend here :) Also, though I haven't really read it completely yet, here is that link I promised for the "standard readme" project: https://github.com/RichardLitt/standard-readme

**Comment by dougwilson** [comment]
@crandmck from our meeting I had wrote up https://github.com/mysqljs/mysql#contributing semi-recently and think it's a good jumping off point for a contributing / tests section.

**Comment by gireeshpunathil** [comment]
closing, as we have a readme and contributing section already. please re-open if that is not the case
