### ISSUE TITLE
YouTube channel

### ISSUE THREAD

**Issue by dougwilson** [expressjs/discussions#34]
Currently all the TC meetings have been automatically uploaded into my own, personal YouTube account. I don't really care, but if people want to subscribe to the channel to watch new meeting, that is kind of weird. I created a separate YouTube channel a while ago, but just now finished moving all the videos: https://www.youtube.com/channel/UCYjxjAeH6TRik9Iwy5nXw7g

**Comment by mikeal** [comment]
we've been pretty liberally adding people to the nodejs channel who run WG meetings. if you'd like these to be in the nodejs channel instead we can add anyone who runs the meetings. up to you :)

**Comment by dougwilson** [comment]
Thanks, Mikeal, but I don't think it makes sense to join them. I looked at the Node.js channel and it really is Node.js and it's working groups. Since Express.js is not a WG and instead an incubating project that should at some point graduate and leave Node.js, it doesn't make long term sense to me to mix the channels.

**Comment by crandmck** [comment]
Doug created an [Express.js YouTube channel](https://www.youtube.com/channel/UCYjxjAeH6TRik9Iwy5nXw7g) (thanks!) and there's a link to it  in the [Community page](http://expressjs.com/en/resources/community.html) (under "Technical committee").

Unless there's an objection, I'd like to close this issue.

**Comment by dougwilson** [comment]
We can close.
