### ISSUE TITLE
migrate hbs module to expressjs org

### ISSUE THREAD

**Issue by dougwilson** [expressjs/discussions#36]
Email from @defunctzombie :

I would like to propose moving the hbs module (https://github.com/donpark/hbs) to the expressjs organization.

This will allow the project to get more eyeballs for issues (I don't have the same amount of time to maintain it as before) and also make it easier to manage the administrative tasks of the project (webhooks, etc). Github limits what type of admin powers you can grant to projects under a user account and as such it is harder to bring on new contributors and change settings without involving the account holder.

Don (original hbs creator and current user account holder) is ok with the migration and I believe it will benefit the module going forward so that it doesn't stagnate.

How would we proceed with moving it?

cheers,
~Roman

**Comment by dougwilson** [comment]
@defunctzombie who should I add to the org to move the `hbs` module?

**Comment by defunctzombie** [comment]
@dougwilson I think only @donpark can move the repo due to admin limitations on user repos (one of the reasons to move it)

**Comment by donpark** [comment]
hi @dougwilson, thx for accepting hbs module into expressjs.

let me know when I should execute the move and feel free toremove me from the expressjs org once dust settles.

**Comment by dougwilson** [comment]
Thanks, everyone! Sorry for the delay. @donpark I just invited you to be an Owner of the `pillarjs` organization on GitHub to move the `hbs` project into.

**Comment by donpark** [comment]
@defunctzombie can you think of anything we need to do before moving?

**Comment by defunctzombie** [comment]
No but once moved we will need to update the readme badges, CI links,
package file, other webhooks.

I believe github will redirect the old page to the new but if not we will
need a dummy repo directing users to the new location.

**Comment by donpark** [comment]
ok. transfer is in progress.

**Comment by donpark** [comment]
@dougwilson `hbs` has been moved to `pillarjs`. added you as admin as well.

**Comment by defunctzombie** [comment]
Will the project remain there or migrate to the expressjs org? Once it is in the final place let me know and I will update the readme and other links.

**Comment by dougwilson** [comment]
We have never really had this type of module before. With the current structure, pillarjs org should be the final resting place unless any other TC members have an opinion otherwise :)

**Comment by donpark** [comment]
Main motivation for moving `hbs` to *express.js* was to give it the attention it needs given that @defunctzombie no longer can.

Is it your understanding that this move fulfills that need @dougwilson? Do you have someone in the TC or supporters in mind who can take things over and address future needs as they arise? If so, I don't particularly care if it's under *express.js* or *pillarjs.org*.

**Comment by dougwilson** [comment]
Both orgs are Express.js and have the same members, is under the current TC, etc. The different github orgs are simply a way to organize the dozens of modules 😊 I will be subscribing to the repo and making sure it gets the attention it needs. We had a brief discussion of even making it the default template engine for the express generator, which would also help ensure that

**Comment by donpark** [comment]
oops. you replied while I was editing my two-cents worth. What you wrote sounds good although I would rather see `hbs` included in a 'best combo meal' pack of sort for expressjs instead since TJ went to so much trouble to pull things out of it.

**Comment by dougwilson** [comment]
> If not and pillarjs is some sort of open graveyard for expressjs related projects

It is absolutely in no way this. The expressjs org is really only to host express and middleware. Since this module is neither, it is organized into pillarjs, which are the modules that are the building blocks of express, for example the router, the file sending, etc. We have a third org jshttp,but that is for the low level http utilities, which this is not.

I understand if you want to "back out" simply because you expected it to be in the expressjs org, but if that were the case, that org would end up just being a disaster.

> although I would rather see  hbs  included in a 'best combo meal' pack of sort for expressjs instead

Can you elaborate on this point :) ? I'm not sure what it meant, and I would love to understand your vision so we are all on the same page. Until we figure this out, you will definitely retain full control of your repo, so I hope you don't feel trapped in ant way... I am very much willing it has a good home and it is heading into some sort of grave yard.

**Comment by donpark** [comment]
>The expressjs org is really only to host express and middleware. Since this module is neither, it is organized into pillarjs

Now I understand why pillarjs exists and it does make good sense. Description *BYO Framework Framework* confused me.

**Express.js combo meal pack**

The idea is to publish one or more `express-xxx` modules containing `expressjs` and a reasonable collection of middlewares and add-ons like `hbs` that developers typically install with expressjs. `body-parser` for example is commonly installed yet each new comer has to discover and integrate. These 'combo packs' are not boilerplates but more 'deluxe' version of expressjs. Closest example is Eclipse offering Eclipse Classic, Eclipse for J2EE, etc. 

I hope that helps.

**Comment by defunctzombie** [comment]
👍 Thanks for handling the migration. I'll update the links and webhooks. I believe this issue can be closed.

**Comment by dougwilson** [comment]
Awesome everyone! Let me know if there is anything you need :)
