### ISSUE TITLE
Node.js Interactive NA

### ISSUE THREAD

**Issue by dougwilson** [expressjs/discussions#44]
Myself & Rand will be in Austin, TX for the Node.js Interactive NA. This is a meta issue to coordinate any kind of meetups around this conference :) 

@crandmck @wesleytodd

**Comment by wesleytodd** [comment]
I just emailed Irl, who has been running most of the stuff for the node meetup. I linked him to this thread to see what he can think of.

For me I would be happy just to setup a drink up, but something less drinking focused might interest others.  The Gingerman is the usual spot, and I am sure conference attendees and speakers alike will already be heading there at some point.

**Comment by wesleytodd** [comment]
I know @cdnadmin also attends most of the js meetups around and might be interested in this.

**Comment by mikermcneil** [comment]
Hey y'all, what's better:  Tue or Wed night?  @wesleytodd Gingerman sounds great.  (Once we've got a day, @irlnathan or I can make a Meetup event so everybody knows where it's at)

**Comment by wesleytodd** [comment]
Thanks Mike!! I should have thought of you since I knew your github to tag you here.  My bad.  Glad you saw it anyway.

**Comment by dougwilson** [comment]
So I'm going to be in Austin evening 11/28 to evening 12/2. I think @crandmck will be there around the same start time, but leaves earlier from my remembering :)

**Comment by crandmck** [comment]
Yes, I arrive Mon 11/28 (late) and leave on Thurs., 12/1.  Weds 11/30 @6:30pm is our normally-scheduled time for TC meeting, but I would have no objection if that were pre-empted by a F2F meetup.

**Comment by jasnell** [comment]
Looking forward to seeing you all. If those of you who are wanting to attend can stay a couple of extra days through the collaborator summit portion of the conference, then I'm certain we could find a breakout room if you wanted to have a few hours for a collaborative face to face work session. Just let me know and I'll help get the space and time arranged.

**Comment by dougwilson** [comment]
@irlnathan that sounds good to me. Walking distance from the venue to boot!

**Comment by crandmck** [comment]
Works for me!

**Comment by mikermcneil** [comment]
See y'all Wednesday!

Meetup link: https://www.meetup.com/noders/events/235779024/

**Comment by crandmck** [comment]
@dougwilson I believe the meetup time overlaps with the time when we'd normally have the TC meeting... We can either just pre-empt the meeting, postpone/reschedule it, or ... ?   I don't know of any urgent matters that we need to discuss, so I'm fine either way.

**Comment by hacksparrow** [comment]
Can't think of anything urgent either. You guys have a good time!

**Comment by dougwilson** [comment]
@crandmck sorry, I thought we mentioned the potential conflict before :) though I think there wasn't actually a resolution. Yea, especially since there isn't anything really on an agenda that I, you, & @hacksparrow can think of, we'll probably just cancel this one. I'll make a meeting issue to state the status of it. Since we're in Austin, which is home to Sails.js, one of the larger frameworks built on top of Express, it's nice to sit down with the folks around Salis.js :)

**Comment by wesleytodd** [comment]
It was fun to meet @dougwilson and @crandmck in person!  Thanks for coming out everyone :)

**Comment by dougwilson** [comment]
Indeed!

**Comment by crandmck** [comment]
Definitely great to meet everyone who was there last night!
