### ISSUE TITLE
Express TC meeting 12-14-2016 [canceled]

### ISSUE THREAD

**Issue by crandmck** [expressjs/discussions#46]
## Who

The entire community is welcome to tune in and observe the meeting live at the time below. The following people are listed here as explicit invitees to get an email notification about the upcoming meeting:

Invited: 
- @expressjs/express-tc 
- @wesleytodd (observer)
- @tunniclm (observer)
- @sjanuary (observer)
- @ritch (observer)
- @gabeio (observer)

## When

Dec 14, 2016 - [23:30 UTC ](https://www.google.com/search?q=23%3A30+UTC&oq=23%3A30+UTC)

## Where

YouTube Live
- Viewers: TBD
- Participants: TBD

## Agenda

TBD

**Comment by dougwilson** [comment]
Hey Rand, sorry for the late notice, but I just found out I won't be able to make this meeting. You should be able to create the meeting on the YouTube channel directly.

**Comment by crandmck** [comment]
OK, no worries.  The only thing I have today is https://github.com/expressjs/expressjs.com/issues/751.

If anyone has something else they want to discuss, please say so... otherwise, I think we can skip this meeting.

**Comment by gireeshpunathil** [comment]
closing
