### ISSUE TITLE
Videos of Node.js talks by Express TC members

### ISSUE THREAD

**Issue by crandmck** [expressjs/discussions#47]
In case anyone is interested... from Node Interactive North America 2016:

- [Sate of the Union:Express](https://www.youtube.com/watch?v=HxGt_3F0ULg&list=PLfMzBWSH11xYaaHMalNKqcEurBH8LstB8&index=7) by Doug Wilson
- [Beyond the README: Creating Effective Documentation for Your Project](https://www.youtube.com/watch?v=NwUWuD9Idv4&index=5&list=PLfMzBWSH11xYaaHMalNKqcEurBH8LstB8) by Rand McKinney
- [Complete list of videos](https://www.youtube.com/playlist?list=PLfMzBWSH11xYaaHMalNKqcEurBH8LstB8)

Should we put these links (or embed the videos) somewhere on the website?  Doug's is most relevant since it's specific to Express; Rand's is not specific to Express, though it does use expressjs.com as an example in a few places.

**Comment by dougwilson** [comment]
Yes, @crandmck I think they should be put on the website somewhere, at the very least the state of the union talk since it seems a lot of people (understandably) find it very useful :)

**Comment by hacksparrow** [comment]
@crandmck @dougwilson I was thinking Doug's video should be on the homepage. If everyone agrees, I can work on the layout and open a PR.

**Comment by crandmck** [comment]
Sure!  I would request that it _not_ autoplay, because I think many people find that annoying.
Also, since it's somewhat time-relevant, ideally it would be replace or remove it in the future as it becomes less relevant.

While you're at it, maybe you could address #561 to add links to that video and a few others to 
http://expressjs.com/en/resources/books-blogs.html

**Comment by gireeshpunathil** [comment]
closing, looks like there is nothing outstanding here
