### ISSUE TITLE
Express TC Meeting 01-25-2017 [canceled]

### ISSUE THREAD

**Issue by crandmck** [expressjs/discussions#50]
## Who

The entire community is welcome to tune in and observe the meeting live at the time below. The following people are listed here as explicit invitees to get an email notification about the upcoming meeting:

Invited: 
- @expressjs/express-tc 
- @wesleytodd (observer)
- @tunniclm (observer)
- @sjanuary (observer)
- @ritch (observer)
- @gabeio (observer)

## When

Jan 25, 2017 - [23:30 UTC ](https://www.google.com/search?q=23%3A30+UTC&oq=23%3A30+UTC)

## Where

YouTube Live
- Viewers: TBD
- Participants: TBD

## Agenda

- Discuss PR to doc overriding sugar methods: https://github.com/expressjs/expressjs.com/pull/763
- README guidelines per #33.  Is this OK? Can we add these to our doc/contribution guidelines?
- Other issue clean-up (can these be closed?):
   - #38 (translated READMEs)
   - #20 
   - #18

**Comment by crandmck** [comment]
@dougwilson Shall I create the YouTube link?

**Comment by crandmck** [comment]
Hm, I thought you gave me rights on the YouTub channel, but I don't seem to be able to... :-(

**Comment by crandmck** [comment]
OK @dougwilson I guess we'll wait for you...

**Comment by blakeembrey** [comment]
@crandmck Do we know if @dougwilson is available? I think he's travelling right now, so may not have updated his calendar to catch this meeting. 

Side note: I think the `expressjs.com` issue referenced is the wrong one.

**Comment by crandmck** [comment]
I don't know if Doug is available, actually.  If he isn't we may have to cancel this meeting since I don't  seem to have rights in the TY channel.

**Comment by crandmck** [comment]
..and you're right about the issue.  S/be https://github.com/expressjs/expressjs.com/pull/763.  Edited original comment. thx!

**Comment by crandmck** [comment]
I guess we'll defer the items above til next meeting.  None are urgent anyway :-)

**Comment by dougwilson** [comment]
Hey guys, really sorry I have been traveling as @blakeembrey said and didn't realize what day of the week it even was :S but would have said I couldn't attend this meeting anyhow. @crandmck you should be but IDK. What we should do is get together some time online outside of the normal TC meeting and check out what we need to get setup so you can host the meetings, as I definitely don't want to be the bottleneck :)

**Comment by crandmck** [comment]
Thanks, I'll ping you some time so we can make sure I can host the meetings. I thought it was set up already, too!

**Comment by gireeshpunathil** [comment]
meeting happened long back, closing. Please re-open if anything is outstanding here.
