### ISSUE TITLE
Open Collective for Express

### ISSUE THREAD

**Issue by hacksparrow** [expressjs/discussions#52]
I propose we create an [open collective](https://opencollective.com/) for Express and have it linked on expressjs.com.

@expressjs/express-tc

**Comment by dougwilson** [comment]
I was recently talking to the folks behind Gitter and they are about to launch a new npm-centric team service that is probably better than the open collective. I said we'd probably try it out, but of course if we go open collective, then probably not...

**Comment by hacksparrow** [comment]
Ok, let's wait and see.

**Comment by dougwilson** [comment]
But yes, we should set up something soon, whatever we feel soon should be. If we think we want it quickly, then open collective is probably the only thing. If not, we can see what the terms of the Gitter stuff will be and how they compare or whatever and then choose.

**Comment by hacksparrow** [comment]
Any idea when they are launching? If it's gonna be couple of months, it's best to start with open collective and evaluate Gitter's option when they launch.

**Comment by dougwilson** [comment]
And re Gitter stuff, Gitter of course used to be Gittip, but from my understanding what Gittip (and maybe open collective) do were not super legal and the banking system backing Gittip pulled out from them, so they had to scramble and really reinvent themselves. I'm not sure how open collective is different from what Gitter used to do, and of course their web site doesn't explain and they are suspiciously in a closed beta, so it's hard to know if open collective will end up going through the same melt down.

The new Gittip stuff coming up is supposed to be totally on the up-and-up for the laws & stuff. I believe most of the issues revolved around U.S. income tax laws AFAIK (i.e. if they were obligated to report to the IRS, if they were allowed to be shuttling money through the bank system they were using, etc.).

For the when, I'm trying to remember, but don't remember exactly. From my recollection it was within a couple months (?). My conversation was https://youtu.be/B-kC1SEx31g but it's looong :)

**Comment by hacksparrow** [comment]
@dougwilson my suggestion was primarily driven by the insane amount of effort you have and continue to put on Express, so I will leave the decision up to you.

**Comment by mikeal** [comment]
The foundation is also looking at ways to fund smaller efforts like this but it's still pretty early so we don't have anything actionable we can share yet.

Before you go looking for funding you might want to think about what you'll actually want to spend the money on. I've seen a bunch of projects raise money on there but very few have talked about what they actually did with the money.

One side effect of raising money is that donors believe their donation will likely fix whatever concern they have with the project. If you don't set expectations up front about what the money is for and what it will solve you're opening it up to a lot of potential backlash from unmet expectations you never even expected.

Another thing you might want to consider is teespring. It's a crowd funding site for t-shirts and you can set the price to whatever you like, so it could be cost neutral or could raise money for the project if you figure out what you want to spent it on.

**Comment by wesleytodd** [comment]
closing this in favor of #69 (nice).
