### ISSUE TITLE
expressjs.com domain asset

### ISSUE THREAD

**Issue by dougwilson** [expressjs/discussions#54]
I've been thinking about the question @mikeal proposed back at NINA 2016 regarding Express graduating from the Node.js incubating projects program. I think that there are things going well, but certainly I think there is a question (to me? to @crandmck ?) around what that would mean for the ownership of expressjs.com domain and the Cloudflare account that backs it.

Thoughts, @mikeal ?

**Comment by crandmck** [comment]
I think this may come down to (a) whether Node.js Foundation would require expressjs.com domain to be transferred to them and (b) if so, whether IBM would do so.  TBH, I don't know the answer to either, though if needed I could investigate (b).  

Re CloudFlare, I think we want to, we could probably just set up a CF account for Express and start using that.  I guess it hasn't been an issue so we haven't pursued that....

**Comment by dougwilson** [comment]
AFAIK expressjs.com domain is under the ownership of the Node.js foundation currently, but I'm not clear on that. @mikeal @jasnell do you happen to know?

**Comment by jasnell** [comment]
If it's not yet it should be. @rmg @sam-github can you follow up and check to see if the transfer actually happened?

**Comment by crandmck** [comment]
> If it's not yet it should be. 
My bad, I forgot that had been decided already.

**Comment by rmg** [comment]
From `whois expressjs.com` it looks like it is still owned by IBM (via the cscglobal.com registrar they use).

As for CloudFlare, @crandmck is correct. The way forward is for someone to either
 - create a CloudFlare account for express and add the domain to it
 - add the domain to the Node Foundation's account

In both cases we'll probably have to jump through some hoops to "verify" the domain and then delete the domain from StrongLoop/IBM's CloudFlare account, which I imagine will involve a period of time where the domain won't resolve properly.

IIRC, this is the kind of hassle that ultimately led to expressjs/expressjs.com#668 being closed. :-(

**Comment by dougwilson** [comment]
The domain name has since been moved to foundation ownership.
