### ISSUE TITLE
Express TC meeting 03-08-2017

### ISSUE THREAD

**Issue by dougwilson** [expressjs/discussions#55]
## Who

The entire community is welcome to tune in and observe the meeting live at the time below. The following people are listed here as explicit invitees to get an email notification about the upcoming meeting:

Invited: 
- @expressjs/express-tc 
- @wesleytodd (observer)
- @tunniclm (observer)
- @sjanuary (observer)
- @ritch (observer)
- @gabeio (observer)

## When

Mar 8, 2017 - [23:30 UTC ](https://www.google.com/search?q=23%3A30+UTC&oq=23%3A30+UTC)

## Where

YouTube Live
- Viewers: http://youtu.be/Kl2oKDeuz6A
- Participants: https://hangouts.google.com/hangouts/_/ytl/VAEVusndOP2GgQ6aqkLWWjVSYTDkZY4r_FhyyPtmlsI=?eid=118089942299398580717&hl=en_US&authuser=0

## Agenda

- Please propose some topics, otherwise we _could_ skip if we don't think there is anything.

**Comment by wesleytodd** [comment]
Is it worth talking about any of these that are marked for 5.x but not merged?

https://github.com/expressjs/express/pulls?q=is%3Apr+is%3Aopen+label%3A5.x

**Comment by dougwilson** [comment]
Some of them are simple merges that just haven't happed (yet), while others maybe. We do have an agenda label for the main repo when we set everything up, so perhaps we could start using it if someone brings up in an issue to add it, idk

**Comment by dougwilson** [comment]
Also, it seems I will likely miss or be late. Rand can setup

**Comment by wesleytodd** [comment]
Makes sense, I guess I was unsure if the 5.x tag mean't for sure going to merge, or just still under consideration for merge.  Just wanted to speed along any "under consideration" issues :)

**Comment by crandmck** [comment]
Hi, I'm getting it set up now.  Give me a couple mins.

**Comment by crandmck** [comment]
Should be working now.

**Comment by crandmck** [comment]
So, unless I did something wrong setting up the Hangout On Air, no one has shown up yet.
I don've have anything to discuss, except maybe https://github.com/expressjs/discussions/issues/54.

**Comment by wesleytodd** [comment]
So canclled?

**Comment by crandmck** [comment]
Doug hasn't shown up yet.... Still waiting for him.  Do I have to start the live event for you to join @wesleytodd ?

**Comment by dougwilson** [comment]
For @wesleytodd point, I think underlying is that we / I need to write up a document explaining the labels for anyone, including future collaborators.

**Comment by gireeshpunathil** [comment]
meeting happened long back, closing. Please re-open if anything is outstanding here.
