### ISSUE TITLE
Express TC Meeting 4/5/2017

### ISSUE THREAD

**Issue by crandmck** [expressjs/discussions#58]
## Who

The entire community is welcome to tune in and observe the meeting live at the time below. The following people are listed here as explicit invitees to get an email notification about the upcoming meeting:

Invited: 
- @expressjs/express-tc 
- @wesleytodd (observer)
- @tunniclm (observer)
- @sjanuary (observer)
- @ritch (observer)
- @gabeio (observer)

## When

Mar 22, 2017 - [23:30 UTC ](https://www.google.com/search?q=23%3A30+UTC&oq=23%3A30+UTC)

## Where

YouTube Live
- Viewers: TBA
- Participants: TBA

## Agenda

- Please propose some topics, otherwise we _could_ skip if we don't think there is anything.

**Comment by crandmck** [comment]
I don't have anything, but I was going to suggest that we consider changing the meetings to monthly, since we often end up skipping meetings anyway.

**Comment by crandmck** [comment]
Well if @dougwilson doesn't show up soon, we can cancel (again).  

We may also want to consider switching to TC meetings only "as needed" since there hasn't been a lot of activity lately.

**Comment by LinusU** [comment]
I don't have anything specific either 👌

Changing to monthly sounds good for me

**Comment by crandmck** [comment]
OK well it looks like Doug can't make it this time.... 
Since no one has raised any items for discussion, we'll cancel this meeting.

**Comment by dougwilson** [comment]
So I didn't respond right away :) I _can_ attend tonight, but usually the TC is really supposed to get invoked for discussions needing to get together. So perhaps even if we want to move to once-a-month, the following proposal may help:

We can create a "tc-agenda" label in the repos (probably as-needed) and just use whatever is on that label a few days prior to the scheduled meeting to drive the agenda / if the meeting is even going to happen.

Thoughts?

**Comment by crandmck** [comment]
Makes sense.  So, then the meetings would only occur each month if there are agenda items to discuss... 

Works for me.  Do we need to have an official TC vote on that small procedural change, or can we just take the number of +1's on the comment above as "aye" votes?  Latter is fine by me. :-)

**Comment by zackarychapple** [comment]
If someone wants to submit some questions for discussion how do we go about doing that?  I would like to bring up the typescript conversation again.

**Comment by dougwilson** [comment]
You can either open a new issue in this repo or continue the conversation in #7

**Comment by dougwilson** [comment]
And of course you could do the same in the main expressjs/express repo :) really wherever and if someone feels really strongly it's in the wrong place, it can be moved, so don't feel bad wherever you open it :) the expressjs/express has the biggest audience if you're going for that, and this repo does tend to only have the main collaborators as the audience.

**Comment by gireeshpunathil** [comment]
meeting happened long back, closing. Please re-open if anything is outstanding here.
