### ISSUE TITLE
Removing myself from 'owner' role

### ISSUE THREAD

**Issue by jasnell** [expressjs/discussions#60]
Hey all,

Very happy overall to see that things here are going well. Given my current focus and activity (and complete lack of activity over on this side of the house), there really is no longer any justification for my account being configured as an owner in any of the expressjs github orgs. If there are no objections, I'll go ahead and convert my account to an "outside collaborator" by the end of the day.

/cc @expressjs/express-tc @mikeal

**Comment by dougwilson** [comment]
Sure, James, that sounds fine to me. Of course, if you could help with getting us access to the expressjs.com domain at all, that would be an amazing send off, but if not, that's cool. Not being able to handle our own domain has certainly hamstrung us from really saying Express is an independent project, so we continue to cling to the Node.js foundation for help on this aspect.

**Comment by jasnell** [comment]
Sigh, I had hoped that would have already been done. Since I'm not at IBM anymore I'm not sure what I can do directly. @crandmck @rmg @mikeal ... would this be something that the three of you could help out on here? The domain ownership does not necessarily need to be transferred but responsibility for management of the domain can be opened. It's actually quite silly that this hasn't been done yet :-(

**Comment by crandmck** [comment]
Unfortunately, I don't have any real visibility into this.  I was depending on @jasnell :-(
That being said, if there's no one else, I can pursue it (but see below).

> The domain ownership does not necessarily need to be transferred but responsibility for management of the domain can be opened. 

I would think @rmg would be our best bet on that front....
