### ISSUE TITLE
express js with es7

### ISSUE THREAD

**Issue by mom3d** [expressjs/discussions#61]
i want to refactor expressjs with es7 as  a final year study project

**Comment by WORMSS** [comment]
So which versions of Node are you willing to stop supporting due to this?

**Comment by med2bled** [comment]
if i want to use 
`import  express from 'express';`

**Comment by WORMSS** [comment]
I thought you were able to do that without any changes to express at all? 

Plus:  
Which versions of Node are you willing to stop supporting if you were to re-write express?  
Is `import express from 'express';` the only benefit from for dropping support for ~400 versions of Node?

**Comment by dougwilson** [comment]
Yes, `import express from 'express'` already works today and I have worked on a few projects who were using babel to do exactly this -- no changes to Express currently required. I'm not certain what the ask is here exactly -- you're of course welcome to rewrite / refactor express as any project you like: it is licensed under the MIT license. I assume your question is would the rewrite / refactor be incorporated back into the main project, is that a correct assumption?

**Comment by med2bled** [comment]
i am always missing around here in GitHub checking JavaScript libraries but i don't know  where to to start contributing i am highly motivated to be involved in opensource libraries . i want to start now . i am able to understand the code but i want to test, debug,add something to the community .

**Comment by gireeshpunathil** [comment]
inactive, closing. Please re-open if there is anything actionable here.
