### ISSUE TITLE
Web application using Angular, Express, node, Sequelize and SQL Server

### ISSUE THREAD

**Issue by baacheey** [expressjs/discussions#63]
Hi,

We are starting to develop a new web application using Angular, Express, node, Sequelize and SQL Server.
Are there any known issues with the stack listed?

**Comment by dougwilson** [comment]
None that I am aware of, at least.

**Comment by baacheey** [comment]
Thank you!
This is our first project on node and angular. Are we on the right path with the stack chosen?
Please let me know if you recommend an alternative to Sequelize and/or Express.

**Comment by dougwilson** [comment]
Hi @baacheey it's hard to really recommend anything different without understanding what you're setting out to solve. There are many possible stacks, none of which are a one-size-fits-all, so it would depend on many factors. The stack you're looking at is common and many folks use it without issue.

**Comment by baacheey** [comment]
Thank you. That helps.

**Comment by gireeshpunathil** [comment]
closing as resolved
