### ISSUE TITLE
Location for linking to example production source code

### ISSUE THREAD

**Issue by dougwilson** [expressjs/discussions#64]
So on our site, we currently have the page http://expressjs.com/en/resources/companies-using-express.html which is nice, but there are also projects in which we should probably link to their source code too, for examples on real applications using Express so users can study their source code as further examples.

Does this sound like a good idea? If so, we do you think we should show case them?

**Comment by crandmck** [comment]
Yes, it's always good to show good examples and best practices.  

The only drawback is that we'd want to be sure that any code we "showcase" is reviewed to _some_ degree by someone with good technical knowledge (e.g. you, @dougwilson).  IOW, if we're going to hold something up as an example, we'd want to be sure it's actually a good example....

**Comment by klyburke** [comment]
@crandmck I would love to see a "Production examples" page. @dougwilson wondering if you have any more thoughts on this?

**Comment by vprasanth** [comment]
This would be great for teams looking for resources to prepare for medium to large projects. There's a lot of "Getting started" samples, but not as easy to find samples around real world applications. Having "vetted" resources would be fantastic!

**Comment by dougwilson** [comment]
This seems more appropriate as an expressjs.com issue (I opened it here, sorry!) and since it's been pretty dead, I'm just going to close it. If we think it should be reopened, we can do so and also just do it in the expressjs.com repo :)
