### ISSUE TITLE
Copyright of Express logo for commercial educational purpose

### ISSUE THREAD

**Issue by Andrewyg** [expressjs/discussions#65]
I was wondering can I use Express logo in my online course? Can I use it if I earn money from it (commercial use)?

**Comment by dougwilson** [comment]
Hi! The contents of our site, including the logo, are under the following license: https://creativecommons.org/licenses/by-sa/3.0/us/

This license allows you to use it in your online course with attribution.

**Comment by Andrewyg** [comment]
@dougwilson But since it's under cc by-**sa**, it meant it needs to be license under the same license which cannot be done since I'm starting course on platform which will earn profit (each course has the price). If I didn't get wrong as long as it requires paying the product (course) can't be licence under creative common right?

**Comment by dougwilson** [comment]
Hm, I am not sure. The full license text is https://creativecommons.org/licenses/by-sa/3.0/us/legalcode which may clarify. Without knowing the details of the course and how content is used in the course specifically it's hard for me to speculate (which is all I can really do without being a copyright lawyer).

**Comment by crandmck** [comment]
I believe you can use the logo (with attribution) in your presentation/course, without having the overall work be CC-licensed.  See https://academia.stackexchange.com/questions/48375/using-images-with-cc-by-sa-license-in-slides-or-a-thesis

As a practical matter, I think using the logo in a training course is fine, as long as you attribute it (i.e. link to expressjs.com) and it's clear that you are not claiming to be part of the Express project or TC, or to "own" the image/project, etc.  

Caveat: This is just my opinion and I am not a lawyer.

**Comment by accidentalmeme** [comment]
The license states:
'[A] "Collective Work" means a work, such as a periodical issue, anthology or encyclopedia, in which the Work in its entirety in unmodified form, along with one or more other contributions, constituting separate and independent works in themselves, are assembled into a collective whole ... This Section 4(a) applies to the Work as incorporated in a Collective Work, but this does not require the Collective Work apart from the Work itself to be made subject to the terms of this License'

**Comment by gireeshpunathil** [comment]
is this still outstanding?

**Comment by dougwilson** [comment]
Let's assume answered
