### ISSUE TITLE
Change badges to use badgen.net

### ISSUE THREAD

**Issue by styfle** [expressjs/discussions#66]
@amio Created a new badge service called https://badgen.net that appears to load badge much faster than the overloaded https://shields.io service.

Would you be interested in switching badges to use this newer, faster service?

**Comment by dougwilson** [comment]
From https://github.com/amio/badgen-service :

> Shields […] leaves more and more broken badges in READMEs. 

I have been seeing that a lot recently, so this would be a welcome change.

Still trying to find any kind of policy for their service irt tracking / whatnot. I may need to contact the owner(s) if I cannot find anything online.

**Comment by styfle** [comment]
> Since images automatically load when users open the README files in various things like their editors, we want to be courteous to our users 

Good point! I'm not sure about the tracking policies.
What kind of tracking is (or is not) acceptable?

I tagged @amio so we should hear something shortly.

**Comment by amio** [comment]
Hi everyone! As the tracking concern, currently Badgen's tracking & logs:

- Google Analytics on doc page ([home](https://badgen.net), [/docs/packagephobia](https://badgen.net/docs/packagephobia), etc.)
- Live badge request time on server side, like:
    ```
    2018-08-10T02:26:56.940Z  #npm dm/nuxt: 45.646ms
    2018-08-10T02:26:56.960Z  #npm license/nuxt: 290.487ms
    2018-08-10T02:26:57.113Z  #circleci github/nuxt/nuxt.js: 603.977ms
    2018-08-10T02:27:08.619Z  #npm v/npm: 712.037ms
    2018-08-10T02:27:10.198Z  #npm dt/camaro: 33.761ms
    2018-08-10T02:27:10.371Z  #appveyor ci/tuananh/camaro/master: 651.733ms
    2018-08-10T02:27:10.391Z  #npm v/camaro: 488.829ms
    2018-08-10T02:27:10.411Z  #travis tuananh/camaro/master: 508.989ms
    ```

I think that could be considered as "no tracking" for badges. Tell me what you thought 🤗

**Comment by dougwilson** [comment]
Thanks @amio ! I vote to move to switch all our badges from shields.io to badgen.net . I will test it on badgeboard first (https://expressjs.github.io/badgeboard/ for the uninitiated). It is pretty slow and sometimes has trouble loading everything for a while now. Should be much better after switching

**Comment by LinusU** [comment]
> Live badge request time on server side, like:

As long as it doesn't include the IP address I don't see a problem with it 👍

**Comment by dougwilson** [comment]
I found the following bug which would be a blocker to switch our badges from shields.io to badgen.net until it is sorted out:

https://github.com/amio/badgen-service/issues/96

The summary is that coveralls badges on shields.io show the repo code while badgen.net is showing the most recent pr instead, which means our coverage badge would not be meaningful in at way on badgen.net service :(

**Comment by amio** [comment]
It's fixed now :D

![](https://flat.badgen.net/coveralls/c/github/expressjs/morgan/master)
https://flat.badgen.net/coveralls/c/github/expressjs/morgan/master

**Comment by styfle** [comment]
Should we add "install size" to the badge board now?

**Comment by styfle** [comment]
Closing since this is complete and install size is available since https://github.com/repo-utils/badgeboard/pull/34

See https://expressjs.github.io/badgeboard/
