### ISSUE TITLE
Financial Support For Express

### ISSUE THREAD

**Issue by wesleytodd** [expressjs/discussions#69]
I was wondering if anyone had any interest in something like this for Express?

https://tidelift.com/
https://www.wired.com/story/netflix-open-source-wants-developers-get-paid/

The idea is that the maintainers commit to certain things to the company (things which are most likely already being done), but in exchange get paid for it via a subscription fee paid to Tidelift.  I am not personally looking to "quit my job and do open source", like the wired article talks about, but I can for sure say that if there was a small financial incentive I might put more effort into finishing up my open PRs :)

I think there are many challenges to a project like Express adopting a paid model, but I thought it would be worth at least bringing up.

**Comment by WORMSS** [comment]
I don't really have much weight around here.. but I know I hate the idea of this.

**Comment by wesleytodd** [comment]
Would love to know why in more detail.  Opinions matter for stuff like this.  And I cannot speak for others, especially people who have put in much more effort than I, but I am not looking for income for this work.  But sometimes having a little carrot can help incentivize people to spend more time.

**Comment by WORMSS** [comment]
Maybe the reason for tidelift to exist is not clear.

**Comment by wesleytodd** [comment]
I think they provide a service which a company with significant resources would be more willing to pay for.  I support a few things via direct support or over Open Collective, but I cannot imagine asking my employer to contribute directly to an Open Collective managed by individual contributors.  A company like this provides more concrete things to the contributors, making large scale contributions for support more reasonable.

**Comment by niftylettuce** [comment]
I've reached out to @piamancini from Open Collective to see if she wants to chime in here with her thoughts.  I personally don't think that Tidelift is any different than Patreon or PayPal.me links, and I feel like Open Collective is way more transparent, open, and less gimmicky with slogans like "You can win $10K for open-source!" as Tidelift is.

**Comment by wesleytodd** [comment]
Yeah, I support Beaker Browser on Open Collective and like it and the experience well enough.  I am not strongly opinionated on this space so would love to hear wide ranging input.  The only reason I posted Tidelift was that the OP article was posted in my company internal Slack :)

**Comment by piamancini** [comment]
thanks @niftylettuce for the ping.

I'm happy to answer any questions on how Open Collective works! I'm not going to speak as to what Tidelift is doing since my experience with them is very limited. I think they want to work with individual maintainers instead of communities. That, at least, is my understanding from my few interactions with them. 

> I support a few things via direct support or over Open Collective, but I cannot imagine asking my employer to contribute directly to an Open Collective managed by individual contributors

@wesleytodd not sure I'm getting your point, many companies support projects on Open Collective [facebook](https://opencollective.com/fbopensource), [Airbnb](https://opencollective.com/airbnb), [trivago](https://opencollective.com/trivago), just to pick three. 
Why do you think your employer wouldn't be able to support a collective?

**Comment by wesleytodd** [comment]
Thanks for the input @piamancini!  I did not mean to imply that *my* employer would not use Open Collective.  Just that some might, because traditionally non tech companies who do not have an understanding of how this all works might like the model where they get some "perceived value" out of the exchange.

**Comment by wesleytodd** [comment]
Maybe I need a better pitch on Open Collective than I have previously gotten.  My only interaction has been backing one project, but maybe OC would be a better fit here.  I will look at it more from the project viewpoint, and would love any resources you could send my way for this @piamancini.

**Comment by devsumanmdn** [comment]
@wesleytodd can I ask what is stopping us from setting up financial support currently? I can't find anyone completely against it in this discussion and it's almost 1 year.

[opensource.guide](https://opensource.guide/getting-paid/) has some notable ways.

**Comment by wesleytodd** [comment]
Hey @devsumanmdn, I don't think there is anything clearly stopping us.  I have some concrete ideas about this topic, but they are currently secondary to the work we have been talking about in the last few TC meetings.  With so many topics to juggle I have not been able to follow up with this one.

There are many ongoing conversations around support or sustainability in the OSS maintainer space.  So my hope is that once these different groups can find a good path forward, Express can just adopt that.  The problem is that an important project like Express has a lot at stake, so adopting the wrong funding model could have big consequences.  Personally I just would want to make sure we choose the right model.

> opensource.guide has some notable ways.


Thanks for this resource, I will check it out!

**Comment by wesleytodd** [comment]
Sorry, I should have added references to the "many conversations":

https://github.com/nodejs/package-maintenance/issues/192
https://github.com/feross/funding/issues/13
https://github.com/npm/cli/pull/187
https://github.com/feross/thanks

**Comment by dougwilson** [comment]
The typical issues have been talked about here, and are even talked about (without a given solution) in the link @devsumanmdn posted, specifcially:

1. How are taxes handled with the funds collection?
2. What are the funds actually going towards and how to make it transparent around their distribution.
3. When funds are distributed, what are the tax implications / how is that handled?

**Comment by dougwilson** [comment]
Because Express is a project of several people (1) and (3) are relevant, which may not be as hard to answer if the project was just a single person (likely reported as a 1099-K from a payment processor of the donations if you are in the US, for example). But with more than one person, either one person will need to be the central point of collection (and uses their US tax information for the accounts / whatever) or another entity would need to be used to accept and manage the funds (like Tidelift) with the downside being that there is overhead there where they need to be paid for the service of the accounting, etc. and they may not be able to distribute to people in certain regions of the world.

It's a lot to consider just from that point of view, and as opensource.guide even points out, it's probably better to come up with a clear goal on what the funds are needed for so it makes sense with what happens.

**Comment by devsumanmdn** [comment]
@piamancini ping

**Comment by wesleytodd** [comment]
So I have a lot of thoughts on this, but I have other plans for today, so I will just say this:

There are many ways to solve the problems around accepting financial support, how it is distributed, and all the logistics questions. I raised this issue to start the discussion on if we might ever want to, and if so why.  I think we should leave the "how would we do it" to a discussion after we decide we would want to, as it is pointless otherwise.

As for why we might want to:

1. We could pay maintainers (even if it is a coffee a week it sets a good precedent that the work is worth $$$) 
2. We could use it for tooling and services which cost money
3. We could fund education on the project
4. We could pay for things like a doc site visual refresh, or more translations, or other paid services
5. We could offer feature bounties
6. We could pass support down to our dependencies (the ones which are not maintained by us)
7. Buy swag :)
8. ...Many other things with go into a supporting and promoting a modern OSS project....

Anyway, clearly I think having some budget is a good thing for a project.  If we others agree with me, then I think can start discussions of what specifically of these things would we plan to do, and how would we accept that financial support.  But the first decision is yes/no on doing it at all.

**Comment by piamancini** [comment]
> How are taxes handled with the funds collection?

I can only speak for Open Collective. 

You have two ways with OC: 

a) you can either bring your own legal entity (and bank account), in which case your entity deals with taxed and they'll depend on the type of structure you have and the location. 

b) you can choose a host (fiscal sponsor), essentially an organization that provides you with the legal entity and bank account. The Open Source Collective (oscollective.org) is the fiscal sponsor 90% of projects on OC use. This is a non profit entity so there's no income tax from your donations.  

> What are the funds actually going towards and how to make it transparent around their distribution.

Transparency is built into open collective, there's no way of receiving or withdrawing funds without a public record. This helps a lot. What you spend the money for it's mostly up to you as long as it's funding going towards your mission. In this case, you can expense flights/accommodation to conferences/meetups, operation costs, services (design, etc) and engineering time (invoices). 

> When funds are distributed, what are the tax implications / how is that handled?

When you submit an invoice, that's accounted for as income for you, so you should include it in your filing. The host will need a W9 or W8 tax form and takes care of filing the relevant 1099s forms (US based). This is not the case for reimbursements (when you submit a receipt for an expense)

**Comment by feross** [comment]
@dougwilson Not sure if this has been suggested before, but OpenCollective provides a solution to some of the issues you've pointed out. Specifically, they can help by eliminating the need to set up a legal entity to collect the funds, as well as the need to file taxes. I believe that you can tell TideLift to send funds to the OpenCollective account where they will start to collect until there is a use for them. When someone wants to claim some of the funds, they submit a proposal which will be made transparent to the community. I think they take a 10% of the funds as a fee for that service. I've never used it myself, so I can't recommend it from personal experience. I'm just sharing what I've heard. Anyway, hope this is helpful!

**Comment by wesleytodd** [comment]
In no way do I want this to become self promotion, but today I was accepted into the GH Sponsors Beta.  I wrote up my page over the weekend, and have committed to taking any support I get and funneling it directly into the projects I work on.  Clearly Express is the largest and most in need of support :)

So, I wanted to see how people feel about me starting to organize some community things if I can get some 💸 to work with?  I was thinking of a bunch of ideas for the project, but feel a bit weird asking as an individual as opposed to people directly funding the project.  Does anyone object to me doing this?  Does anyone want to collaborate on this?

There has not been much traction since I posted this a year ago, but maybe all the community enthusiasm around funding OSS (thanks @feross and the infamous expirement of 2019 😛) we can make some headway!

Also, if anyone has feedback on my sponsor page I would love it.  It is really hard to write something which is effectively asking money for things I already do for free, so helping me squash any impostor syndrome would be great!

https://github.com/users/wesleytodd/sponsorship

**Comment by blakeembrey** [comment]
I just had a quick pitch from Carbon Ads which sounds like a good way to bootstrap funding without requiring sponsors or subscriptions. The ads are fairly small and can be seen on http://getbootstrap.com and http://laravel.com/docs. We could look at doing something similar with http://expressjs.com, and I believe it'd be a non-insignificant source of funding. I think we'd be able to combine this income with something like Open Collective on the legal side to collect and distribute funds within the organization to pay for whatever is needed.

**Comment by wesleytodd** [comment]
I am on the fence on ads.  I agree these are unintrusive but I think the incentive is structure is not aligned with how OSS projects are managed IMO.  I guess that if it raised enough money I might change my mind :P (see the perverse incentives at work!!)

So how much money could these ads raise for us?

**Comment by blakeembrey** [comment]
He mentioned $1-2/1000 impressions on the call, at a million visits per month that would be $1000. Could you elaborate more on the incentive structure concerns?

**Comment by wesleytodd** [comment]
It was brought to my attention that the project has some money waiting for us to claim it in [Open Collective](https://opencollective.com/express).  If there is no opposition I can start the process of getting that setup so we can claim the money and figure out what to do with it.  My preference would be to work with the Foundation to make sure this is done correctly, and preferably have the account somehow linked to the foundation.

**Comment by dougwilson** [comment]
Yes @wesleytodd , that would be awesome 👍 . The biggest hurdle I have encountered, I think, has been what to _do_ with the funds, ultimately. It has always felt weird to turn it into any kind of "pay ourselves" for some reason (sorry, not sure how to articulate it just yet). But I have seen things like use for sending merch to groups who want to have local meetings (like stickers) or other small-scale things like that to show support, but I'm not sure what that does, ultimately (though I wouldn't oppose it). I would love to hear any thoughts you have on what the money can be used for, just as a general curiosity for myself.

**Comment by gireeshpunathil** [comment]
IMO, a better decision can be taken based on the amount at hand, and the `rate` of `cash inflow` . For example, anything between `pay ourselves` (which brings a question of who `us` are etc.) and buying and distributing goodies such as T-shirts / stickers (in the decreasing order of the amount and frequency)

For the current instance, ($460) I suggest to devide the money among the express committers - bringing great motivation to the contriutors and triagers!

In general, I believe one of the best way to feel proud of working in express is to utilize it, and probably talk about it!

**Comment by dougwilson** [comment]
Yea, I have seen at least one project use raised funds for something like that -- to help send someone from the general community (vs the main contributors) to talk about the project at a conference (even a local one) in order to both spread the word of the project and as a way to get people involved who may not be able to otherwise (due to the cost of travel, etc.). I know the current amount at hand may not be enough for something like that, but that doesn't mean it can't be in the future, of course.

Usually the other reason I have seen the money distributed as merch and/or travel, etc. vs pay the committers, is because the reporting can be complicated for each person and the tax agencies in which they are under, as getting paid for being committers is considered earned income in many tax jurisdictions.

**Comment by gireeshpunathil** [comment]
I agree on the tax related implications; but if the amount grows substantial and the inflow becomes steady, we may be looking at seriously considering it as an income source? And considering that way, IMO, is well aligned with the `purpose` envisaged by donors.

For that reason, I suggested to utilize it as `cash` itself, to kick-start in style. Not a strong opinion though!

**Comment by dougwilson** [comment]
Right. I'm not familiar with all the jurisdictions, but in the US (where I reside) even $1 is required to be reported as income, carving off all the various taxes from that, and likely causing the people who receive it to file must more complicated tax forms. That is not a super concern for the project itself, but there is a threshold where if the amount goes above $600 to any one person, the entity who is giving the money has to file documents with the US IRS as well, assuming the entity that is giving this money is based in the US. I'm not sure if each US committer in this case would also need to fill out a W-9 for it to be collected by whatever the entity who is distributing the money is. That is likely why hopefully, if the idea is to actually _pay_ folks for their work here, the OpenJS foundation can provide the guidance on how to achieve doing this.

**Comment by gireeshpunathil** [comment]
makes sense! 

/cc @jorydotcom @joesepi - can you pls advise or guide here?

**Comment by jonchurch** [comment]
In this vein, here's a post from Babel about their "Funding Plans" from 2019 when they started soliciting financial support https://babeljs.io/blog/2019/11/08/babels-funding-plans

**Comment by ghinks** [comment]
@wesleytodd @dougwilson @jonchurch I am not sure of what the state of the OpenCollective account is. I have a question though. If there were willing patrons that wanted to contribute today do we have the necessary alignment with @piamancini to be able to own and disperse those funds . If not we need to work on that first.

**Comment by UlisesGascon** [comment]
We will re-open the conversation in https://github.com/expressjs/discussions/issues/228. Feel free to join the discussion there as I will close this issue
