### ISSUE TITLE
Disable x-powered-by by default?

### ISSUE THREAD

**Issue by pluma** [expressjs/discussions#72]
This is a follow-up on https://github.com/expressjs/discussions/issues/39 from 2016.

So it's late 2018 and express still out of the box adds the x-powered-by header even though the security guide on its own website recommends disabling this in production.

If the official stance is that the best practice is to disable this in production and there's no obvious benefit of using this in development, can't we simply cut the noise and disable this out of the box?

Is there a rationale why this is still enabled by default? If the desire is to support it for development for some reason I'm not aware of, can't this be done with a `NODE_ENV` check instead?

In the long run I would love to see express being secure by default and hiding e.g. the default error page (with full stack trace and everything) behind a "debug mode" the same way more full-featured frameworks do but this seems like a small change with an easy security win.

**Comment by dougwilson** [comment]
No, it's not going to happen. There have been long discussions on this default and there is even a recorded TSC meeting on the topic. I will follow up with links, but there is not going to continue to be bikeshed on this topic.

**Comment by dougwilson** [comment]
Looks like all the relevant discussions are linked from the issue you already linked to.

**Comment by dougwilson** [comment]
Also, I'm only referring to the  x-powered-by header above; the stack trace is already controlled by NODE_ENV and the idea is to change the default value for NODE_ENV to production in 5.0 instead of the current default of development. There is an issue tracking the changing of NODE_ENV default in the main express repo.

**Comment by dougwilson** [comment]
This is the link to the NODE_ENV defaulting to production tracking issue: https://github.com/expressjs/express/issues/3346
