### ISSUE TITLE
The logic of the "View.prototype.lookup" method.

### ISSUE THREAD

**Issue by DevelAx** [expressjs/discussions#75]
The logic of the [`View.prototype.lookup`](https://github.com/expressjs/express/blob/master/lib/view.js#L104) method is unclear to me. 
```JS
View.prototype.lookup = function lookup(name) {
  var path;
  var roots = [].concat(this.root);

  debug('lookup "%s"', name);

  for (var i = 0; i < roots.length && !path; i++) {
    var root = roots[i];

    // resolve the path
    var loc = resolve(root, name);
    var dir = dirname(loc);
    var file = basename(loc);

    // resolve the file
    path = this.resolve(dir, file);
  }

  return path;
};
```

What is the purpose of converting `this.root` to the `roots` array and then iterating over it? Even if the array contained more than one element, all previous values of `path` would still be overwritten with the last one. 

Could you make it clear, please?

**Comment by WORMSS** [comment]
I am not sure about duplicating the array.
But I think you are forgetting the conditional in the for loop. If resolved path does does not equal a fasley, then we jump out. So it won't always be the last element in the array.

**Comment by DevelAx** [comment]
@WORMSS yep, I overlooked that condition check, thanks! The loop and array still look to be redundant though.

**Comment by WORMSS** [comment]
Are you thinking root is a single value and being pushed into a new array? Instead of root being an array already and it's concatenating all the values into the new array?

Again, I am unsure why it's being duplicated, but the fact that it's an array means it does need iterating over

**Comment by DevelAx** [comment]
@WORMSS you're right. I missed it in the documentation. It's said that it could be:

> A **directory or an array of directories** for the application's views. If an array, the views are looked up in the order they occur in the array.

Now `[].concat(this.root)` makes sense for the case when `this.root` is a string.
