### ISSUE TITLE
Box shadow leaving strip at bottom of image?

### ISSUE THREAD

**Issue by JainJude** [expressjs/discussions#83]
Hey all, very new to really messing with CSS and I can't seem to figure out what's going on here. On the site I'm working on there are several flags lined up like the ones in the image, and I've added a hover effect on mouse over with a little box shadow. However, anytime the hover effect is applied to the flag image, there's that little strip of white added to the bottom of the image and I can't seem to figure out what's causing it, although I know it has something to do with the box shadow.

For the box shadow I have:

box-shadow: 0 20px 20px rgba(0, 0, 0, 0.23);

Would really appreciate any help!

**Comment by WORMSS** [comment]
This more seems like a question for StackOverflow than expressjs.

**Comment by wesleytodd** [comment]
Agreed.  This issue tracker is for discussion of Express features and community topics.  Nothing to do with CSS.  Good luck with your issue!
