### ISSUE TITLE
ProcessWire CMS

### ISSUE THREAD

**Issue by JainJude** [expressjs/discussions#84]
Hi everyone

I just wanted to share what absolute treasure I found today: ProcessWire

I was always looking for a good CMS, with a nice backend, easy to use, easy customizable and one with which I can create MY styles/templates easily. Today I found ProcessWire and I'm blown away. It is just amazing and has so much potential!

Has anyone of you worked with it before? What is your story with it? Any modules I need to know or tips for a beginner?

Thanks

**Comment by WORMSS** [comment]
This seems like spam (or a way to increase the CMS's visibility on google) rather than a topic to discuss express development.

**Comment by wesleytodd** [comment]
A PHP cms?  Yeah I agree this is not the right place for a discussion.
