### ISSUE TITLE
Status Board

### ISSUE THREAD

**Issue by wesleytodd** [expressjs/discussions#87]
I mentioned in the last TC meeting that I have been working on a status page which pulls the tags and other meta information about the project.  Here is the progress: https://pkgjs.github.io/statusboard

This tool pulls from a list of github projects and builds a level db where we can then build a page from, it takes a while to build the index.  

What I have now for the UI is pulling a list of "tagged issues", which if we started using "top priority" it would list here as we discussed in the last meeting.  I thought it would also be nice to incentivize new users to show the "top contributors" across all of the repos.  Then I created a similar thing to the badge board, which I will expand with more features in the future.

I was shown https://devstats.cncf.io/ as an example of showing activity across projects, so I was thinking I would add graphs of contributions, maybe even a github commit board style thing, but for all activity across the repos.

Once I finish it up I was thinking we could add a link to it on the website and point new contributors there as a place to start.  Thoughts and feedback welcome, but remember this is completely a work in progress!

**Comment by gireeshpunathil** [comment]
is there any pending action on this?

**Comment by wesleytodd** [comment]
The only remaining things to do before merging are listed in the pr here: https://github.com/expressjs/statusboard/pull/1

Feedback and getting that merged is all.  I will close that since we have that PR.
