### ISSUE TITLE
Express CoC

### ISSUE THREAD

**Issue by wesleytodd** [expressjs/discussions#91]
https://github.com/openjs-foundation/cross-project-council/blob/master/CODE_OF_CONDUCT.md

Since we are member project, I think we should adopt the code of conduct recommendation form the OpenJSF.  It should be as simple as copying that document into the projects.

They re developing reporting methods and a bunch of other stuff we would benefit from if we went this route.  The other big goal of doing this would be for new contributors and people thinking about getting involved, it would give them confidence that we have a procedure in place to help in the case of issues.

Thoughts?

**Comment by jonchurch** [comment]
Closing as this got merged in https://github.com/expressjs/express/pull/4143
