### ISSUE TITLE
Double Back Slash

### ISSUE THREAD

**Issue by netfoundry-ui** [expressjs/discussions#93]
I feel like this was brought up before but I need to return a json string value as:

for response.json()

{"DateEntered":"\\/Date(1571879845+0000)\\/"}

but if I set the string to \\\\/ it returns

{"DateEntered":"\\\\/Date(1571879845+0000)\\\\/"}

and if I set the string to \\/ it returns

{"DateEntered":"/Date(1571879845+0000)/"}

maybe its stupid, probably a dumb question but I cant find anyone resolving this and the DotNet service trying to read this value keeps failing.

Thanks!

**Comment by WORMSS** [comment]
I didn't think forward slashes needed to be escaped?

**Comment by wesleytodd** [comment]
Hi @netfoundry-ui, not a dumb question, but this might not be the best place to ask it.  The discussions repo is more about feature development discussion on Express, not support requests.  I would recommend asking this question on StackOverflow or in the Express Gitter.  There is a large community available to help, but most don't really follow this repo.  Good luck!
