### ISSUE TITLE
Express YouTube Channel

### ISSUE THREAD

**Issue by wesleytodd** [expressjs/discussions#94]
https://github.com/nodejs/package-maintenance/issues/284#issuecomment-559639798

> So I can move it to another Google Account, and seems like everything will stay intact. Is there like a general org account to move it in to or should we make a brand new Google Account just for this (and if so, how should we manage the 2FA on it)?

I don't have a strong opinion on how we manage this, but it seems to me that if we want to share it so that other can run the meetings in @dougwilson's absence then it should probably be under a new account just for this.  What are everyone else's thoughts?

If so, should we use a lastpass to share the credential like the OpenJSF did for the zoom credential?

**Comment by dougwilson** [comment]
Yep, I agree, if there is no like JS account to put it under, we can just make a brand new Google Account that is just for Expressjs stuff and move the YouTube channel into that account.

**Comment by wesleytodd** [comment]
@mhdawson do you think this would fit under a node or foundation youtube?  What do other projects do?

**Comment by blakeembrey** [comment]
Not sure about LastPass, but 2FA is supported by 1Password and it's what I use at work too. Looks like you can get a free team with https://github.com/1Password/1password-teams-open-source. A quick scroll shows Babel in their list 😄 

But yes, moving things into shared accounts sounds like a good plan.

**Comment by wesleytodd** [comment]
The reason I mentioned LastPass is that it is what the OpenJS Foundation used to share their zoom account with us.  I am fine if we chose to use 1Password, but it would mean we need both (as we plan to use their zoom account for the TC meetings moving forward).

**Comment by wesleytodd** [comment]
When I first read that I thought you meant 2FA for the service, but now I am thinking you mean 2FA for the shared account.  I am not sure if that is supported on LastPass, which might be a great reason to use something different.  We should figure that out and share it with the OpenJSF in case that changes how they plan to move forward.  Also of note, they will pay for an account for all of us it is not free I think.

**Comment by mhdawson** [comment]
So far other projects don't use the OpenJS youtube channel. Since only one stream can be recorded at a time for an account I'd suggest keeping an Express youtube account.  For the node.js and OpenJS accounts we then add other people as "managers" and any one of them can start streams/manage the videos in the youtube account when logged in as their own google account.

**Comment by dougwilson** [comment]
Sorry meant to follow up here. I went to create a new Google account for expressjs and among other things it is requiring a phone number to make the account. There doesn't seem to be a good method to make an account that is not supposed to be a person without going through the business account process, though I didn't try that yet to see what it needs.

**Comment by wesleytodd** [comment]
@mhdawson, do you think this could be something the OpenJS Foundation would manage for member projects?  That way there is a phone on the other end in case we need to recover the account or something.

**Comment by mhdawson** [comment]
@brianwarner you show as the primary owner of the Node.js youtube account and then we have a good number of people who are managers.  This would likely make sense for the Express account as well. Can you help out on this front?

**Comment by brianwarner** [comment]
So, it's an interesting question.  Short answer is yes, I would certainly be happy to manage the account as we do with Node and OpenJS, though I've also run up against that same issue where you need a phone number to verify an account.  It turns out, you can only verify two accounts per year that way.

I've reached out to the YouTube team to ask if there's an alternate way to get verified, as I have multiple other accounts which need the same thing and only one phone number.  I'll poke again.

**Comment by gireeshpunathil** [comment]
where do we stand on this?

**Comment by dougwilson** [comment]
Either need a phone number that doesn't belong to an individual in order to create a new Google Account against (which is the current problem; YouTube account is associated with an individual) or need an existing OpenJS Google Account to move the Express YouTube channel into (a Google Account can have many YouTube channels).

**Comment by mhdawson** [comment]
@brianwarner have we every considered using something like twillio or equivalent.  Cost is pretty low (I think maybe $1/month ish and small cost for minutes/texts). I would allow us to forward the validation to another number.  I know there are some problems with SMS validation using this kind of service but if there is an option for an actual phone call that seems to work pretty well.,

**Comment by brianwarner** [comment]
I think it just needs to be any cell phone number.  It doesn't get used for anything other than the verification code.

**Comment by jonchurch** [comment]
I think that youtube's ["Brand Accounts"](https://support.google.com/youtube/answer/9367690) are setup for this type of situation. If Node/OpenJS is adding managers to a youtube channel, they must have already set up a Brand Account, as I don't think that feature is available without it.

I don't think creating a new personal account and sharing credentials is the best way to manage this.

You do need to provide a phone number when creating a brand account, but I can't find any information if that number is tied in some way to the account, or just used as 2 factor for your own account when creating the Brand.

OpenJS could create this brand account and act as it's owner, then the existing Express channel can be moved into it and folks added as managers of the channel.

**Comment by brianwarner** [comment]
Just following up, I can create the brand account, though I'll need someone's phone number to receive the verification SMS (since mine has met its cap for the year...).  @dougwilson, do you want to connect on this and we can get this crossed off?

**Comment by dougwilson** [comment]
I have turned the Express.js channel into a brand account and can add any needed Google Accounts to access & mange it. @wesleytodd if you're interested in access, just email me your Google Account name. We can add additional folks as needed now.
