### ISSUE TITLE
Restructure TC Meeting With Triagers

### ISSUE THREAD

**Issue by wesleytodd** [expressjs/discussions#95]
As came up in the triage sync meeting is that we will want some time set aside for discussion triage topics.  As the goal of this is to have these new contributors participate as much as possible in the project, I think it would be reasonable to restructure the TC meeting and schedule to accommodate an additional 30min to discuss triage topics.

It would be great if we could make a decision and set a time for early-mid January to kick off the changes.  That way we could promote it at Node Interactive and get a good group of people together for the first meeting.  If we are not ready to change the whole TC meeting then we should at least set a time for the triage sync.

For reference: https://www.youtube.com/watch?v=Y0nqjseQbN0

cc: @expressjs/express-tc @expressjs/triage

**Comment by wesleytodd** [comment]
One other thing we might consider is changing the name to "Community Meeting"?  I think one of the goals is to make sure everyone feels like they can speak up and be included.  If they are not "on the tc" it might make people feel less comfortable giving input and feedback.  Maybe this is not a real issue, but wanted to at least bring it up.

**Comment by dougwilson** [comment]
As for the name, I think it just came from following the Node.js setup; the actual name doesn't matter at least to me :D 

Who should be in charge of the decision above? The length of the meeting has always been wishy-washy and so adding 30 mins at the end would just be a function of the invite. Setting a new time and day of the week, ok the other hand, should just be a doodle. I know last I remember there was going to be a triage meeting early Jan. Was this discussed at that time at all?

Just trying to understand what landed here in the interim of time :)

**Comment by wesleytodd** [comment]
I think we didn't finalize any meetings changes.  If we are going to try and have a TC meeting this week or next then I think we should discuss this so we can move forward on it.

**Comment by jonchurch** [comment]
I'm happy to attend the next meeting and chat about Triage or just observe 👍

**Comment by ryhinchey** [comment]
I'm not officially a triager yet but have been starting to help out.  I'm happy to attend a meeting about triage

**Comment by wesleytodd** [comment]
@ryhinchey, I am sorry for the hold up, life has been really busy lately, and realizing that I had multiple groups to manage I started to write automation for this instead of just doing it manually.  My engineer brain led me to think automating it was a better use of my time lol, what was I thinking 😛

**Comment by ryhinchey** [comment]
no worries @wesleytodd! life happens

**Comment by gireeshpunathil** [comment]
we are already practicing this, so just wondering if there is anything left here:
 - just close
 - document the current process and close

**Comment by jonchurch** [comment]
We haven't talked about triage specific topics in a meeting yet, only peripherally. I'm not sure yet what I'd want to see discussed in regards to triage in the currently scheduled TC meeting.

I'd be interested in some kind of recurring checkin w/ @expressjs/triagers folks. Hashing out interest and if our timezones allow that is for another issue though.

IMO next actions for this issue would be: 

* Decide if we want to dedicate a small chunk of time in meetings to checkin about triage
* Add something to triage doc encouraging triagers to attend the weekly TC meeting, and linking to the schedule

**Comment by dougwilson** [comment]
Yea, I think the last 4-5 meetings have all been generally TC items vs triage-specific topics. I could see maybe some possibilities here:

1. Make sure there are at least some triage specific topics on the agenda and perhaps split it to 30 mins TC and 30 mins triage (not strict, just general).
2. Have a separate triage-specific meeting we get set up with some triage folks an account to host the meeting, etc. Align timing to the folks important to that meeting: triagers.

Idk, just throwing some stuff out. We have in the TC meeting the triagers as speakers, but it would be that way regardless of what type of Express member meeting it is, so I would assume that the goal is to discussion triage-specific topics among triager audience, right?

**Comment by ghinks** [comment]
Yes I think that @jonchurch has made a good suggestion. It would be good to put some triage items on the agenda.

**Comment by Sushmeet** [comment]
Having some time set aside for triage specific discussions would help to discuss direction and handling of some issues. The biggest barrier I find for triaging now, is to decide when an issue can be closed. So essentially some guidelines as to how to objectively look at an issue, and still respect the ideologies of the express project.

**Comment by dougwilson** [comment]
Ok, so I am going to be opening up the TC meeting issue for this Wednesday, so it sounds like the triagers would like to take approximately half the time to discuss some triage-specific issues, is that right? Don't need to know what they are specifically right now, but wanted to just get an idea for the general break down for this week's TC meeting, as I don't want to put too many TC things in it and then not get the triage things out of it, haha. For example, what @Sushmeet asked for I think is excellent, and we should get covered ASAP so you can feel good/comfortable/whatever sooner rather than later.

IMO this is ultimately part of the 5.0 effort, as the entire triage system had the initial goal to distribute a lot of the day-to-day tasks to free up the core folks to both get 5.0 out the door and distribute more knowledge to further spread out the work over time.

**Comment by Sushmeet** [comment]
Another topic I would appreciate some guidance with is, our company is doing a survey and one of the questions that was asked was how the company could help support open source projects and why?

I can answer why quite easily. But the how, the only think I could suggest to my company was to let me contribute during work hours. They are open to suggestions so if there venues that could help support express it would be great to know.

**Comment by dougwilson** [comment]
This discussion has been superseded by #118
