### ISSUE TITLE
Express Twitter

### ISSUE THREAD

**Issue by wesleytodd** [expressjs/discussions#97]
I grabbed the twitter handle https://twitter.com/UseExpressJS

What do you all think about making this the official twitter for the project?

**Comment by helio-frota** [comment]
I think it is good for the project to have a twitter account, so :+1:

**Comment by gireeshpunathil** [comment]
definitely a great idea!

but tbh, I didn't like the handle name much! sorry!

It does not look very natural! Isn't there a better name?

**Comment by wesleytodd** [comment]
Naming is important and I tried many other variants but all were taken. The reason I went with this is that it reads like the English sentence “you should use express” as well as it being one of the main “express” apis `.use()`.

If you can find a better available name I am fine with that, suggest away!

**Comment by wesleytodd** [comment]
Ok, well since there has been no opposition, I will move forward with this.  For now I will just start tweeting about things, but this weekend I will go ahead and open pr's to the website and other resources where a twitter account should be listed.

**Comment by dougwilson** [comment]
Definitely no opposition here. It'll be nice to have an announcement/whatever channel on that platform.

**Comment by jonchurch** [comment]
Any clue who runs https://twitter.com/expressjs ? Last post was in 2014, twitter doesn't reclaim inactive accounts that aren't violating a trademark, but maybe if someone asked nicely?

**Comment by dougwilson** [comment]
> Any clue who runs https://twitter.com/expressjs ? Last post was in 2014, twitter doesn't reclaim inactive accounts that aren't violating a trademark, but maybe if someone asked nicely?

See https://github.com/expressjs/discussions/issues/16

**Comment by wesleytodd** [comment]
TBQH, I think the current handle is fine, but if we can land that one it would be nice.

Also as an update, we have ~800 followers already: https://twitter.com/UseExpressJS

**Comment by dougwilson** [comment]
Folks will just follow whatever we list. I have no issue with the name.

**Comment by dougwilson** [comment]
I think we can close this since the twitter account is there now, so nothing really left to discuss :)
