### ISSUE TITLE
request for a TC meeting to discuss express 5 release

### ISSUE THREAD

**Issue by gireeshpunathil** [expressjs/discussions#99]
as per https://github.com/expressjs/express/issues/4195#issuecomment-590057521

please include this in the agenda:
 - user feedback so far on the alpha releases
 - decide whether `5.0.0-alpha.7` can be cut into express 5.0.0
 - critical blockers if any
 - milestones, owners, checkpoints, commitments, availability matrix

**Comment by dougwilson** [comment]
@expressjs/express-tc and OP, do we think this Wednesday Feb 26, 2020 - 23:30 UTC would be good, or do we need until next week for any conflicts?

**Comment by wesleytodd** [comment]
This time works for me!  

Sorry everyone, with my new position at work I have been slammed.  I intended to follow up better on some of this stuff, but paid work comes first!  I posted https://github.com/expressjs/express/pull/2237#issuecomment-570058548 on Jan 1 with optimism :).  But in general I think we need to have a team agreement on what to do with those remaining items on the list.  A TC meeting for this would be great!

I also propose that we ensure that we have enough time so that we reach final decisions and don't let it hang longer if possible.  It would be awesome if as many project participants can come as possible, so we should also tag @expressjs/triagers.

**Comment by dougwilson** [comment]
I would suggest that we even have a TC meeting starting this Wednesday and again every Wednesday until we actually have the release complete, at a minimum. I feel like doing this will go a long way towards preventing momentum from stalling out.

**Comment by gireeshpunathil** [comment]
> do we think this Wednesday Feb 26, 2020 - 23:30 UTC would be good

It is 5 AM (IST) for me, but will make it if others are good with the time.

**Comment by LinusU** [comment]
> do we think this Wednesday Feb 26, 2020 - 23:30 UTC would be good

It's 00.30 for me, but I can also make it work if others are good with the time 👍

**Comment by jonchurch** [comment]
Even if we don't discuss Triage, I would like to attend the meeting to observe, so count me in. 

I believe that time is 6:30PM EST Feb 26th

**Comment by gireeshpunathil** [comment]
@jonchurch - yes, that looks right.

so looks like we are all good for 23.30 UTC! @dougwilson / @wesleytodd - will you pls confirm the meeting and create and share a link?

**Comment by dougwilson** [comment]
Awesome, everyone! The time is definately open to change; it was decided at the time we had a person in Australia, but that is no longer the case. Once we see who is going to be attending, I think we can easily adjust the time to better fit the attendies.

As for a link, if this is going to be over YouTube (which I normally do) the link will be generated day-of. If Wes is going to make a Zoom with the group account, then it would be whatever timeline that works off-of 👍

**Comment by wesleytodd** [comment]
> If Wes is going to make a Zoom with the group account

I can do that if that is what we want.  The YouTube integration is an issue in that case because I don't know if it can connect multiple channels, and it is connected to the OpenJS one I think (or maybe Node?).  I will look around and see how that works and report back.

**Comment by dougwilson** [comment]
Ok. I also realized that YouTube hangouts is no longer a thing, so I would need to use Zoom anyway, but it would be limited to a max length of one hour due to my account type.

**Comment by wesleytodd** [comment]
I asked about this in the OpenJS Slack.  I have not gotten an answer yet, but I am digging around in the Zoom UI and docs to see if we can just connect ours for this meeting.  @dougwilson did you have a last pass account?   I thought I remember them sharing the zoom credentials with both of us?

**Comment by wesleytodd** [comment]
@dougwilson do you have the zoom credential?  Jory said that if you are logged in to start the call and just have the youtube account which owns the channel it will work.

**Comment by dougwilson** [comment]
Sorry, I just got home. I don't actually have a LastPass account, but I can create one if you want to share the credentials to me. Otherwise I can use the Zoom account I made.

**Comment by wesleytodd** [comment]
I am not sure I can, as I don't own the credential.  But if you can make that account and let me 
know which email address, I can try to get them to share it in asap

**Comment by wesleytodd** [comment]
Or you could add the google account after creating the account and share it with me.  I will email you the address I use for last pass just in case.

**Comment by jonchurch** [comment]
Will a zoom link be posted here when it's available?

**Comment by wesleytodd** [comment]
Yep, just waiting to hear from @dougwilson on if he wants to send me the YT creds or what email to share the zoom credentials from the foundation to.

**Comment by wesleytodd** [comment]
Zoom link: https://zoom.us/j/884354313

We will follow soon with the live stream link.

**Comment by wesleytodd** [comment]
The above link can join as viewers.  We are having some technical difficulties with the live stream to youtube.  Feel free to join and if you want to be a part of the conversation just let us know!

**Comment by gireeshpunathil** [comment]
purpose of this issue is solved:

 - a TC meeting happend,
 - discussed most of the requested items,
 - a recurring (weekly) meeting until `5.0.0` is agreed upon 
 - notes taken, next actions identified

so closing. Cheers!

**Comment by helio-frota** [comment]
hi folks not sure if this is the correct channel to communicate this [triage related], but since the issue is closed (and I know you will receive the message) I'm going to PTO for a full month --> March. 👍
